### ISSUE TITLE
Repo addition request

### ISSUE THREAD

**Issue by novaksam** [autopkg/autopkg#167]
I have a repo of recipes I've been working on for a little while now that were part of a pull request for JSSImporter. I've talked with @sheagcraig and all of my recipes will work with his testing release of JSSImporter which has a new method for replacing variables.

My recipes as they currently exist will not work with JSSImporter 0.3.7, so if you'd rather wait until the testing release of JSSImporter goes Master I can understand that. The majority of them do rely on other repos to make pkgs and I'm not sure if it's possible to make 'requirements' when importing a repo (like using git submodules) but I just wanted to make you aware of that.

**Comment by gregneagle** [comment]
...you haven't given us a URL or repo name for your recipes.
You might want to read this: https://github.com/autopkg/autopkg/wiki/Sharing-Recipes

**Comment by novaksam** [comment]
I wasn't sure if I needed to give the url since it wasn't spelled out on that page, my bad.

https://github.com/novaksam/recipes

**Comment by gregneagle** [comment]
We were supposed to guess?

**Comment by novaksam** [comment]
I wasn't sure if you were going to look at my repo list and pick it out; sorry about that.

**Comment by timsutton** [comment]
It's good you documented the various required repos for recipes. Since there are quite a few recipes and many are variants of other existing recipes (@rtrouton, @golbiga, @justinrummel), maybe it would worth clarifying more about how these recipes differ as to how they function with the use of JSSImporter. Also documenting exactly which released version these will be compatible with I think is important. Consider someone who is completely new to AutoPkg and is wanting to find some JSS recipes and figuring out how to use them.

I'm not following JSSImporter terribly closely and I realize Casper's a more complex system to do AutoPkg-ish things with, so I think it's normal there will be more duplication of recipes that make use of different mechanisms to allow overridable behaviour, than there are with Munki recipes.

The beauty of AutoPkg recipe repos is that they're decentralized and so people will maintain different recipes for the same things, but it should be possible for a newbie to discover the differences between similar recipes without needing to understand all the nitty-gritty of how recipes work (which isn't obvious to the newbie).

**Comment by novaksam** [comment]
I've removed a couple of the repo dependencies and updated the README with justifications for the others. I've also explained how my recipes are setup so a new user would be able to better understand how things work.

**Comment by timsutton** [comment]
Looks good! Thanks - new repo is set up here:

https://github.com/autopkg/novaksam-recipes
