### ISSUE TITLE
Add my slack recipe to autopkg

### ISSUE THREAD

**Issue by killahquam** [autopkg/autopkg#168]
Please add my slack recipe to autopkg
https://github.com/killahquam/killahquam-recipes
Thanks

**Comment by arubdesu** [comment]
Hey Quam, great work! I'm not trying to sound picky, but (even though it passes plutil's checking and works) you've got a stray closing tag in your pkg recipe [here](https://github.com/killahquam/killahquam-recipes/blob/master/Slack/Slack.pkg.recipe#L7). I'd also use their app identifier, ```com.tinyspeck.slackmacgap``` for the pkg, rather than just '[com.Slack](https://github.com/killahquam/killahquam-recipes/blob/master/Slack/Slack.pkg.recipe#L15)'. 
I'm also big on the codeSignatureVerification step being added to download recipes, but that's a somewhat contentious thing it seems. If you were interested, it's done like so, after an unarchiver step to place the binary in a downloads subfolder of the recipe cache dir:
```
<dict>
	<key>Processor</key>
	<string>CodeSignatureVerifier</string>
	<key>Arguments</key>
	<dict>
		<key>input_path</key>
		<string>%RECIPE_CACHE_DIR%/downloads/%NAME%.app</string>
		<key>requirement</key>
		<string>identifier "com.tinyspeck.slackmacgap" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = BQR82RBBHL</string>
	</dict>
</dict>
```
You could also disable it by default with a DISABLE_CODE_SIGNATURE_VERIFICATION boolean to give folks the option of whether they want it.

**Comment by killahquam** [comment]
Thanks Allister, I will look into it and make the needed changes.
Good feedback as always
Quam

**Comment by killahquam** [comment]
All set, please let me know if there is anything I may have overlooked.
Thanks again!

**Comment by arubdesu** [comment]
Awesome, have you tested it with code signing enabled? Looks like some chars encoding got swapped [here](https://github.com/killahquam/killahquam-recipes/blob/master/Slack/Slack.download.recipe#L45)

**Comment by killahquam** [comment]
Thanks, All should be good now including code verification. Thank you very much. Let me know if anything.

**Comment by timsutton** [comment]
The way you included the `DISABLE_CODE_SIGNATURE_VERIFICATION` argument for the CodeSignatureVerifier processor brings up an important distinction about how input variables work. Any variables given explicitly to a processor via the `Arguments` dictionary (as you do [here](https://github.com/killahquam/killahquam-recipes/blob/47e8ea1470f33342a288de3102ffd2f4ea85cdaf/Slack/Slack.download.recipe#L49-L50)) are _not_ overridable. Variables that exist in a recipe's `Input` dictionary are, and then these are either substituted in steps later using % signs (like [this](https://github.com/killahquam/killahquam-recipes/blob/47e8ea1470f33342a288de3102ffd2f4ea85cdaf/Slack/Slack.download.recipe#L26)), or are simply used internally by the processor, but not expected to be defined explicitly in every recipe file (such as `MUNKI_REPO`).

Another similar example is the use of `pkginfo` in every Munki recipe. Several of the Munki-related processors know to look for this special variable and do things with it, but one typically isn't passing in `pkginfo` directly in the processor Arguments - instead it's defined up top in a place where it can be safely overridden.

CodeSignatureVerifier does already try to output some helpful usage info about `DISABLE_CODE_SIGNATURE_VERIFICATION` if the verification step fails, but if you want to put it in your recipe as a usage indicator, make sure that it's done in the Input section and then left out of the processor's Arguments dictionary altogether.

**Comment by killahquam** [comment]
Thanks Tim, Changes were made. Let me know.
Thanks
Q

**Comment by timsutton** [comment]
Done, and available here:

https://github.com/autopkg/killahquam-recipes

**Comment by killahquam** [comment]
Thanks Tim. Awesome... I am IN :)

**Comment by timsutton** [comment]
Since we already have some context here: `DISABLE_CODE_SIGNATURE_VERIFICATION` was something we added as a way to disable the verification steps for cases where a recipe is failing for one issue or another related to the code signature verification step. As such, it's not set by default, functioning as if it's empty or false. It's no harm for you to leave it in your Inputs as a hint, but you may want to set it to true so that it's verifying by default.

**Comment by killahquam** [comment]
Will do. Thank you!

**Comment by killahquam** [comment]
Tim,
I have it set by default to true or are you seen something else??
Q

**Comment by timsutton** [comment]
Sorry, too many double negatives - I meant to suggest you set it to false so that it's _not_ disabled, which is the same behaviour as if someone would run any other download recipe (with a CodeSignatureVerifier step) with no additional overrides or switches.

**Comment by killahquam** [comment]
Gotcha, will do it right now. Thank you very much!
