### ISSUE TITLE
Add Repo Request

### ISSUE THREAD

**Issue by seansgm** [autopkg/autopkg#175]
Please consider adding the following [recipes](https://github.com/seansgm/autopkg-absolute-recipes)

**Comment by timsutton** [comment]
Great! A couple comments:

1. Your `Identifier` key is not of the form `local.*`. AutoPkg uses that as a default identifier prefix when creating overrides, so while it doesn't prevent your recipes from being overridable, it would probably cause confusion if anyone is looking at identifiers and trying to pick out their overrides from your recipes used as the `ParentRecipe`.
2. You should remove `.pyc` files from the repo, and you may want to add these to a `.gitignore` so that others they don't accidentally get re-added.
3. The Daylight recipe is an Absolute recipe like your others but it's missing the `.Absolute` in its name.

If this repo is going to only contain Absolute recipes, do you want the new repo name to reflect that? (ie. "seansgm-absolute-recipes"

**Comment by timsutton** [comment]
Sorry, I meant that your `Identifier` key shouldn't start with `local.*` - instead it's best to adopt the conventions used in other recipe repos (see autopkg/recipes for example).

**Comment by seansgm** [comment]
Initially I pulled recipes from Absolute,
http://forums.absolute.com/download/file.php?id=398&kb=1&sid=3dbeb6ec9a0707ed468c491c4b181458

So the Identifier is how they defined it.  I thought about changing it, but
wasn't sure what was more confusing, so I left as was.
You're right, I need to remove the pyc
Again, the Daylight is how it came from Absolute.

Any recipes I've added beyond the downloaded ones from Absolute I kept to
the same convention, hence they all start local.*

I'm happy to change them all if you think I should and rename Daylight.  I
just decided they were better served as a git repo than as a zip from
Absolute.

**Comment by timsutton** [comment]
But does this mean that Absolute themselves publish recipes on their forum? Would it make sense to get that author involved with this repo, and have them publish it directly themselves? A zipfile of recipes is a good start, but there's a hope that whatever gets published to recipe repos will be maintained over time.

I can see why the identifiers were named that way, as these look mostly like they were made as overrides (which are in fact complete, first-class recipes). Since I haven't been following @tburgin's work on the AbsoluteManageExport processor too closely, and since people usually make recipes by looking at other recipes as examples, it might be worth pinging him on whether this use of his processor makes a good model for other recipes. (In terms of override-ability, the way the processor is called (not via the new 'shared processor' namespace, etc.)

**Comment by tburgin** [comment]
@seansgm I would suggest using AbsoluteManageExport as a shared processor.
  *  https://github.com/tburgin/AbsoluteManageExport

Here is an example of an AdobeFlashPlayer recipe that I use internally. I use this type of format for just about all my recipes.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Description</key>
	<string>Creates an Absolute Manage package (.amsdpackages), imports it into the Absolute Manage Admin console and uploads it to the Absolute Manage Server.</string>
	<key>Identifier</key>
	<string>gov.nih.nimh.github.burgin.NIMH-Recipes.AdobeFlashPlayer</string>
	<key>Input</key>
	<dict>
		<key>NAME</key>
		<string>AdobeFlashPlayer</string>
	</dict>
	<key>ParentRecipe</key>
	<string>com.github.autopkg.pkg.FlashPlayerExtractPackage</string>
	<key>MinimumVersion</key>
	<string>0.4.0</string>
	<key>Process</key>
	<array>
		<dict>
			<key>Processor</key>
			<string>com.github.tburgin.AbsoluteManageExport/AbsoluteManageExport</string>
			<key>Arguments</key>
			<dict>
				<key>dest_payload_path</key>
				<string>%RECIPE_CACHE_DIR%/%NAME%-%version%.amsdpackages</string>
				<key>sdpackages_ampkgprops_path</key>
				<string>%RECIPE_DIR%/%NAME%-Defaults.ampkgprops</string>
				<key>source_payload_path</key>
				<string>%pkg_path%</string>
				<key>sd_name_prefix</key>
				<string>(OSX AutoPkg) </string>
				<key>payload_name_prefix</key>
				<string>~(OSX) </string>
				<key>import_abman_to_servercenter</key>
				<true/>
			</dict>
			<key>SharedProcessorRepoURL</key>
			<string>https://github.com/tburgin/AbsoluteManageExport</string>
		</dict>
	</array>
</dict>
</plist>
```

**Comment by seansgm** [comment]
Should I be cracking on with this then or remove them as you've decided not
to add them yourself?

**Comment by tburgin** [comment]
@seansgm I host my recipes internally for a number of reasons. I think it is great that you are posting these! You just need to get a few things sorted so the recipes are inline with convention. It depends on your workflow. Post and host here if you are going to be using and maintaining these recipes.

  *  Set your Identifier for these recipes. It would be something like 
```
com.github.seansgm.autopkg-absolute-recipes.AdobeFlashPlayer
```

  *  Remove the whole `StopProcessingIf` stuff.  AbsoluteManageExport checks against your SD database for duplicates.
  *  Add or remove any Arguments you wish for AbsoluteManageExport

**Comment by tburgin** [comment]
If you do go with using AbsoluteManageExport as a shared proc, be sure to set the `MinimumVersion` --> `0.4.0`

**Comment by seansgm** [comment]
Please review changes. Think we are there now

**Comment by tburgin** [comment]
@seansgm The few that I sampled look great! Thanks for being the first, that I know of, to post proper Absolute Manage Autopkg recipes! Yay!

**Comment by timsutton** [comment]
Sorry for the long delay adding these. Welcome! Just added them as 'seansgm-recipes':

https://github.com/autopkg/seansgm-recipes

If you'd rather specify in the repo name that they're absolute recipes (ie. seansgm-absolute-recipes) feel free to rename the repo, which you should have access to do.
