### ISSUE TITLE
Please add my recipes

### ISSUE THREAD

**Issue by macvfx** [autopkg/autopkg#182]
Please add my recipes that I've created. User name: macvfx. Repo: AutoPkg. These are download and munki recipes for Final Cut Library Manager, X27, MDRP and Compressor Repair. I used Allister's recipe generation utils.

**Comment by timsutton** [comment]
Hi Mat,

Oops - you'll want to check your recipe plists' validity. You've got stray dict keys after your `Process` array has its closing tag.  For example:

https://github.com/macvfx/AutoPkg/blob/master/MDRP.download.recipe#L40-L41

Usually any Unarchiver steps would go into children of the download recipes, assuming you need to unzip files (which is common with Sparkle downloads).

Also, a typo in the "Final Cut" part of the name of your `FinalCuLibraryManager` recipes.

**Comment by macvfx** [comment]
Thanks. I'll look into those issues.

**Comment by macvfx** [comment]
Ok. Typo was an easy fix. But I don't see any stray dict keys. I stared at it and they look OK. Is there a good tool to double check? Should I used xmllint?

:)

Mat

**Comment by gregneagle** [comment]
plutil is a good tool for linting plists.

-Greg

**Comment by macvfx** [comment]
Ok. Thanks. Right, of course. Checking now.

**Comment by macvfx** [comment]
OK, I've removed download recipes. I used plutil. I checked and all Munki recipes are good. Stray dict keys in download recipes. Don't have time to fix right now. Removed for now.

**Comment by arubdesu** [comment]
Sorry, this is probably some of [my doing](https://github.com/arubdesu/recipeGenerationUtils). I'll try to clean it up/contribute soon.

**Comment by timsutton** [comment]
I was tipped off about the malformed plist by AutoPkg itself, once I'd added Mat's recipes to my AutoPkg search path:

```
autopkg repo-add macvfx/AutoPkg
autopkg run <whatever>

WARNING: plist error for /Users/tsutton/Library/AutoPkg/RecipeRepos/com.github.macvfx.AutoPkg/CompressorRepair.download.recipe: Error Domain=NSCocoaErrorDomain Code=3840 "The data couldn’t be read because it isn’t in the correct format." (Found non-key inside <dict> at line 53) UserInfo=0x7ff7dfc20c60 {NSDebugDescription=Found non-key inside <dict> at line 53, kCFPropertyListOldStyleParsingError=The data couldn’t be read because it isn’t in the correct format.}
```

Because AutoPkg ends up doing a lot of searching for recipe files on every run it's quite verbose about these warnings when a malformed plist exists in its search paths.

The Munki recipes won't work without the accompanying .download recipes, so let's leave this here until Mat has time to re-add fixed download recipes.

**Comment by timsutton** [comment]
@macvfx Came back to take a look since YVR - now I remember. Your download recipes are not part of this repo at the moment, so the Munki recipes fail because they can't find their parents. You had them before, so maybe they work for you because they're in your local path, but just not committed/pushed?

```
➜  ~  autopkg run CompressorRepair.munki
Didn't find a recipe for com.github.autopkg.download.CompressorRepair.
Search GitHub AutoPkg repos for a com.github.autopkg.download.CompressorRepair recipe? [y/n]: y
Nothing found.
Could not find parent recipe for CompressorRepair.munki
```

**Comment by macvfx** [comment]
Tim,

I Tested the ones that Allister copied to his repo. Both download and Munki versions. Both worked. I tested by copying the recipes locally and running them with autopkg. Are you testing those ones?

:)

Mat X

778-837-1036

**Comment by timsutton** [comment]
Hm.. I can't find those recipes. Normally you'd keep the download and munki recipes together in your repo, that's why it seemed to me that while you have a copy locally, and you'd temporarily removed the broken ones with the formatting issues, you maybe maybe hadn't pushed the fixed versions back up?

I only see the munki recipes here: https://github.com/macvfx/AutoPkg, and don't see download ones anywhere on GitHub: https://github.com/search?q=com.github.autopkg.download.CompressorRepair&type=Code&utf8=%E2%9C%93

**Comment by macvfx** [comment]
autopkg

https://github.com/arubdesu/AutoPkg-1

:)

Mat X

778-837-1036

**Comment by arubdesu** [comment]
@macvfx you need to actually merge the PR for it to be in the repo so Tim can add it... not sure if that will delete the one I didn't address https://github.com/macvfx/AutoPkg/pull/1

**Comment by timsutton** [comment]
Ah - I'd missed all of this discussion. Searching code on GitHub doesn't search forks by default. Mat should merge these and then we should be good.

**Comment by macvfx** [comment]
Ok. Well I'm on the road for 12 hours to Kaslo in the kootenays. If you can do it then... Great. If not. I'll look at it tomorrow or afterwards. Explain clearly what I need to do and I will do it 

:)

Mat X

778-837-1036

**Comment by timsutton** [comment]
It should be as simple as just clicking the Merge button at the bottom of Allister's pull: https://github.com/macvfx/AutoPkg/pull/1, assuming you're happy with his changes!

**Comment by macvfx** [comment]
Sure once I can get a moment to open my laptop. In Princeton. Hot hot hot heat. Long drive ahead. 

:)

Mat X

778-837-1036

**Comment by macvfx** [comment]
Done.

**Comment by timsutton** [comment]
Done!

https://github.com/autopkg/macvfx-recipes

**Comment by macvfx** [comment]
Thanks!

:)

Mat X

778-837-1036
