### ISSUE TITLE
Please Add Repo

### ISSUE THREAD

**Issue by kernsb** [autopkg/autopkg#188]
Please add my repo for sharing:

https://github.com/kernsb/bkerns-recipes

Thanks!

Brandon Kerns

**Comment by arubdesu** [comment]
Hey Mr. Kerns,
Awesome! In anticipation of being forked under the main autopkg organization, you may think of changing the identifier to match your github username, e.g. `com.github.autopkg.kernsb` rather than edu.purdue.cla. There are also Apple printer recipes maintained by @n8felton, [here](https://github.com/autopkg/n8felton-recipes/tree/master/ApplePrinterDrivers), which include HP's, but use a different method(a shared processor) to derive the URL. Also, @jps3 has a Camtasia recipe [here](https://github.com/autopkg/jps3-recipes/tree/master/Camtasia). If you feel your methods may meet others needs better, it would at least help to rename your HP recipe to not overlap with Nate's, and also a note in your readme would help folks decide why to use yours instead. Just my 2¢. Thanks,
Allister

**Comment by kernsb** [comment]
Will do on the identifier. And I'll check out those other options. I actually made these quite some time ago because, at that point, they weren't out there or were broken/unreliable (at least at that time). Never got around to submitting the repo. :)

Thanks!

Brandon

**Comment by kernsb** [comment]
Allister,

Took your advice. HP recipe is gone, as n8felton's is working great for me. Identifiers have been changed  and descriptions added. I have also modified the TechSmith recipes to accept a registration key via an override to be included in the munki and pkg installs.

Anything else I need to do?

Brandon Kerns

**Comment by jps3** [comment]
I would recommend getting into the habit of including and code-signing checks with anything that is signed. It's a Good Idea™ that can help secure the packaging and deployment process. (Brandon: feel free to steal mine from https://github.com/autopkg/jps3-recipes/blob/master/Camtasia/Camtasia.munki.recipe#L35-L45) 

If Brandon's recipes work well (I've not had a chance to test them yet), should I deprecate/remove my Camtasia recipes? I only have one client who uses it, so I did not have need to "embed" any Process-es to handle registration key(s). I don't see any reason to duplicate effort/recipes...

**Comment by timsutton** [comment]
I've just cloned these to AutoPkg here:

https://github.com/autopkg/bkerns-recipes

Nice docs in the README! We always encourage people to resolve duplicate recipes (i.e. your Camtasia recipes if there's no significant distinction between yours and @jps3's), but that doesn't block us adding this repo.
