### ISSUE TITLE
Please add jss-recipes repo to AutoPkg organization.

### ISSUE THREAD

**Issue by sheagcraig** [autopkg/autopkg#189]
@homebysix and myself have been working on standardizing the jss-recipes repo that I originally began to house the recipes for my organization. As this repo gets included by default with AutoPkgr use of JSSImporter, and is used by a lot of JSSImporter users, I wanted to get the recipes included as part of the AutoPkg organization so that they show up in the `autopkg search` results, etc.

We came up with a style-guide and I wrote a recipe validator to ensure that every recipe follows the exact same procedure to make it safe for new users to quickly add a number of recipes to their Casper workflow, and to allow later customization through overrides if needed. You can check all of this work out in the README.

Anyway, all of the work is still in the *testing* branch, as there are significant changes to some of the recipes, and I didn't want to silently change things that drastically for all of the existing users.

Once forked, I'll go ahead and merge testing into master for the new repo, so it will be all set; and I'll notify everyone via the usual means that things have moved.

The url is https://github.com/sheagcraig/jss-recipes

Also, I've done all of the identifiers and documentation with the name `jss-recipes`, so if possible, I'd like that to be the name moving forward.

Thanks!

**Comment by eahrold** [comment]
@sheagcraig,  This is already slated for Version 1.3 We automatically add the repo when JSSImporter is installed. The current status is here [1.3-alpha2](https://github.com/lindegroup/autopkgr/tree/v1.3.0-alpha2/AutoPkgr)

We've actually started subclassing integrations and would love if you would look over it and make sure things looks accurate to you... https://github.com/lindegroup/autopkgr/blob/v1.3.0-alpha2/AutoPkgr/LGJSSImporterIntegration.m

The one thing I haven't quite settled on is what to do with python-jss, i.e to uninstall that component or not. My thinking is that since it's possible, though not likely that someone is using AutoPkgr is using that independently so should __not__ be uninstalled, want to weigh in?

**Comment by sheagcraig** [comment]
@eahrold I think it's extremely unlikely that someone is using python-jss and AutoPkgr. But if they are, I think that they know what they're doing enough to add it back... But I also don't feel like it's a must-remove either. It's small, in the grand scheme of things. And it is managed by the python package management system.

I would vote to just leave it.

The integrations code looks good to me, with the exception that `defaultRepository` still points to my jss-recipes repo; in theory it should get forked into https://github.com/autopkg/jss-recipes soon.

How to handle the transition for AutoPkgr users is one that I am at a loss to handle.

**Comment by eahrold** [comment]
Good point r.e. transition. I'll open up discussion issue once the repo is officially pulled into autopkg.
I'll update the `+ defaultRepository`.

**Comment by timsutton** [comment]
Done - added as `jss-recipes` here:

https://github.com/autopkg/jss-recipes

I realize AutoPkgr may well be using its own GitHub API code to do searches, and it's obviously better for the repo to be part of the autopkg org for better discoverability - just an FYI that you can still do a search restricted to different users using `autopkg search -u`, or as part of your query with the GitHub API. You might know that already, pointing it out in either case.
