### ISSUE TITLE
please add/fork my autopkg recipes

### ISSUE THREAD

**Issue by valdore86** [autopkg/autopkg#192]
Dear autopkg maintainers,

please consider adding/forking my autopkg recipes. They can be found at:
https://github.com/valdore86/valdore86-autopkg-recipes

kind regards,
Frank / valdore86

**Comment by timsutton** [comment]
Done! Forked here:

https://github.com/autopkg/valdore86-recipes

Look great, just one pointer for comments about specific recipes - like you added to your README for KeePassX. If you add such details to the Description key in the recipe plist it will be more visible to users, since it's what shows up in `autopkg info`.
