### ISSUE TITLE
Email or Notification Processor?

### ISSUE THREAD

**Issue by everetteallen** [autopkg/autopkg#193]
I wanted to check if anyone has put together a processor that emails (or other notification types) out.  I want to create a email each time a recipe runs to notify groups, etc on the status of the package (updates, no update, etc).  Considering creating a processor for this but need to not reinvent...

**Comment by timsutton** [comment]
I know @nmcspadden has a "Yo" processor that posts notifications. However most people instead use something like Sean Kaiser's [wrapper script](https://github.com/seankaiser/automation-scripts/tree/master/autopkg), AutoPkgr (which has built-in e-mail reports) or something like Jenkins.

AutoPkg has functionality to output a report with the `--report-plist` option, which can be parsed to determine if there is anything worth reporting. I think it's generally easier to wrap this than to write a custom processor that you run at the end of your run, because you may not necessarily have all the info you want at the time the processor runs.
