### ISSUE TITLE
GitHubReleasesInfoProvider doesn't return version without asset

### ISSUE THREAD

**Issue by arubdesu** [autopkg/autopkg#202]
I know the intended use of GHRIP is to provide a download URL and other associated metadata in one step, but the current 'assets' API object dependency means it cannot be used to only extract the (current) release version. E.g. osquery releases their pkgs on S3, so trying to utilize this processor for only the version(to pass along with the downloaded pkg to our JSS-using friends, since they need that metadata on import) fails with `No release assets were found that satisfy the criteria`.
I was thinking that potentially folks would want to use this to fetch zip's of source code, e.g. dockutil, and make their own pkg with autopkg, but that doesn't return much of anything from the API when using `curl -i "https://api.github.com/repos/kcrawford/dockutil/releases"`. Feel free to mark this 'won't fix'.

**Comment by rtrouton** [comment]
One thing that may impact this is that the alternative is using **URLTextSearcher**, which does not seem to be able to scrape https://osquery.io/downloads/ . This may be because it's a Facebook site and Facebook seems to have blocked scraping for other unrelated reasons:

http://adespresso.com/academy/blog/facebook-scraping-custom-audiences/

**Comment by arubdesu** [comment]
Yeah, and likewise I'm making the assumption the pkgs hosted on S3 are always in sync with the release tags on a different site. I could use URLTextSearcher to return the value from the GitHub page just the same, however, so I leave it up to Tim if he thinks this need matches his use case.

**Comment by timsutton** [comment]
I could see the value in this processor not bailing if there isn't an asset available, since release notes and version are still extracted from the release. It would have to be made clear that `url` will return an empty string, and that `asset_regex` would not have any effect.

Your example for dockutil returns empty for the `/releases` endpoint because dockutil doesn't actually have any releases. GitHub is just listing tags as poor-man's releases in this case, but GitHub has this notion of "promoting" a tag into a release (at which point you add release notes and optionally attach assets).

URLTextSearcher parsing https://github.com/kcrawford/dockutil/releases would be a way to extract a zip/tarball and parse the version at the same time using the `(?P<name>...)` syntax.

**Comment by timsutton** [comment]
As for osquery, curl seems to have no problem loading https://osquery.io/downloads - so if there's an issue with AutoPkg parsing it, it could be an SSL/TLS-related issue.

**Comment by jgstew** [comment]
I had this same issue with: https://github.com/Rem0o/FanControl.Releases
