### ISSUE TITLE
Consider adding my repo.

### ISSUE THREAD

**Issue by portalpie** [autopkg/autopkg#244]
Hello. I found an app that I wanted to manage in munki. Put the URL through recipe robot and such has begun my journey into sharing recipes that others might find useful. The URL is https://github.com/portalpie/portalpie-recipes.git I have tested the mpv recipe and it seems to work. I have not yet been able to get the munki part, just the install.

**Comment by timsutton** [comment]
Great!

Although Recipe Robot helpfully extracts the icon for you, we've been recommending that authors don't include the icons in their repo unless they have the rights to redistribute them. (I'm not sure where mpv stands on that)

Also for what it's worth, the Munki pkginfo generated by the Munki recipe doesn't extract enough version information for Munki to be able to know whether a given version is newer than another, due to the way mpv generates the version info ([this script](https://github.com/mpv-player/mpv/blob/master/version.sh) generates version info used in Info.plist of the form `git-<sha1>`. So it will install one version fine, but depending on the Git SHA-1 used in the next release Munki may not update it.

IMO mpv should really just put the real version numbers into the released versions as part of the project's build process (and leave "git-hash" style versions for ad-hoc/snapshot builds), but one potential workaround would be for you to instead use the GitHubReleasesInfoProvider processor for the download recipe, which will also extract the "0.14"-style version for you, which you could include in the pkginfo version. The versioning of the app bundle itself (the `installs` item in the pkginfo) you'd need to use something like `md5checksum` on a unique file, since they don't seem to include that tagged version anywhere in the app bundle.

Feel free to ignore my advice about the Munki recipe, although if you choose to leave the recipe I'd recommend putting a summary of this info in the .munki recipe Description.

**Comment by timsutton** [comment]
I opened an issue with mpv about the versioning and it was fixed upstream, so the next released version should use the proper version in the app's `CFBundleShortVersionString`.

**Comment by portalpie** [comment]
Hello Tim, Sorry for the slow reply. You are amazing. I need to find a moment to digest your first reply. Thank you so much on the second reply. So impressed.

**Comment by timsutton** [comment]
I'm going through some backlog of recipe repo requests and checked on this one, and looks like you're still working on it. I'll close this one for now, but feel free to re-open it whenever you're ready.
