### ISSUE TITLE
Please add my backupminder recipe

### ISSUE THREAD

**Issue by YesThatAllen** [autopkg/autopkg#268]
my backupminder recipe is also ready for adding.

it's created by Watchman Monitoring, so probably best to create it as

https://github.com/watchmanmonitoring/BackupMinder-Recipe

**Comment by timsutton** [comment]
Since this and #267 are both for Watchman products, they should both be in a single `watchmanmonitoring-recipes` repo, which I've just set up under the `autopkg` org. You can then manage any number of recipes in one logical place going forward.

Since you've done READMEs, you can still leave these in the repos but within their respective subdirectories.

**Comment by YesThatAllen** [comment]
Fantastic. Thank you!
