### ISSUE TITLE
Enhancement request - less strict "legal" package name regex for .pkg recipe.

### ISSUE THREAD

**Issue by goobersmooch** [autopkg/autopkg#272]
The current regex for a legal package name is ^[a-z0-9][a-z0-9 ._-]_$. Could you please broaden the regex on https://github.com/autopkg/autopkg/blob/master/Code/autopkgserver/packager.py#L44 to allow more package naming conventions. Might i suggest changing  ^[a-z0-9][a-z0-9 ._-]_$ to ^[a-z0-9][a-z0-9 ._+-]*$?

In my particular situation, when creating a app.pkg.recipe, if the app name contains '+', it fails with Error Processor: PkgCreator: Error: Invalid package name.

Example excerpt from pkg.recipe that fails with the error:

```
<key>Input</key>
<dict>
<key>BUNDLE_ID</key>
<string>app.name</string>
<key>NAME</key>
<string>App.Name+</string>
</dict>
```

Example excerpt from pkg.recipe that builds correctly:

```
<key>Input</key>
<dict>
<key>BUNDLE_ID</key>
<string>app.name</string>
<key>NAME</key>
<string>App.Name</string>
</dict>
```

Thanks!

**Comment by goobersmooch** [comment]
Lets discuss. See #285

**Comment by gregneagle** [comment]
Let's do discuss, but also post on autopkg-discuss (perhaps pointing here) so more people see the issue.

**Comment by timsutton** [comment]
I agree that it's probably too strict. A name with a `+` in it seems weird to me, but I think we could certainly relax the regex to allow more characters.

It looks to me like the `pkgname` request dict value, after validation, eventually determines part of the file path of the output flat package. I'm not really in favour of restricting characters _except_ that I'd think we should not allow any characters which would be illegal to write to an HFS+ disk, a common network share like SMB, or a Linux filesystem.

**Comment by MagerValp** [comment]
Looks like I'm to blame, and the reasoning is to err on the side of caution. The package name will eventually end up in a filename with character restrictions, as an URL somewhere, and as an argument in a shell command. With proper escaping it should be safe to use just about anything, but as we all know it's all too easy to miss it in one spot. Personally I'd just spell it out as "plus".

If URL escaping is not an issue I could see adding `@` as well, since that's also safe in the shell and all relevant file systems.
