### ISSUE TITLE
CodeSignatureVerifier fails to process path with glob

### ISSUE THREAD

**Issue by workflowsguy** [autopkg/autopkg#282]
With AutoPkg 0.6.1, when I run

`autopkg run -v Dictate4.munki`

I get

```
Processing Dictate4.munki...
SparkleUpdateInfoProvider
SparkleUpdateInfoProvider: Version retrieved from appcast: 13048
SparkleUpdateInfoProvider: User-facing version retrieved from appcast: 4.0.6
SparkleUpdateInfoProvider: Found URL http://www.macspeech.com/release/4.0/de/Dragon%20Dictate%20Deutsch_13048.zip
URLDownloader
URLDownloader: Storing new Last-Modified header: Thu, 30 Oct 2014 15:31:36 GMT
URLDownloader: Storing new ETag header: "433da7-19148a2-506a593682600"
URLDownloader: Downloaded /Users/stefan/Library/AutoPkg/Cache/com.github.workflowsguy.munki.Dictate4/downloads/Dictate-4.0.6.zip
EndOfCheckPhase
Unarchiver
Unarchiver: Guessed archive format 'zip' from filename Dictate-4.0.6.zip
Unarchiver: Unarchived /Users/stefan/Library/AutoPkg/Cache/com.github.workflowsguy.munki.Dictate4/downloads/Dictate-4.0.6.zip to /Users/stefan/Library/AutoPkg/Cache/com.github.workflowsguy.munki.Dictate4/Dictate/Applications
CodeSignatureVerifier
Error processing path '/Users/stefan/Library/AutoPkg/Cache/com.github.workflowsguy.munki.Dictate4/Dictate/Applications/Dragon Dictate Deutsch.app' with glob. 
Failed.
Receipt written to /Users/stefan/Library/AutoPkg/Cache/com.github.workflowsguy.munki.Dictate4/receipts/Dictate4-receipt-20160531-185402.plist

The following recipes failed:
    Dictate4.munki
        Error in com.github.workflowsguy.munki.Dictate4: Processor: CodeSignatureVerifier: Error: Error processing path '/Users/stefan/Library/AutoPkg/Cache/com.github.workflowsguy.munki.Dictate4/Dictate/Applications/Dragon Dictate Deutsch.app' with glob. 

The following new items were downloaded:
    Download Path                                                                                           
    -------------                                                                                           
    /Users/stefan/Library/AutoPkg/Cache/com.github.workflowsguy.munki.Dictate4/downloads/Dictate-4.0.6.zip
```

I don't know what this error is supposed to tell me...

**Comment by gregneagle** [comment]
Did you _write_ this Dictate4.munki recipe? If not, where did you get it? 

```
% autopkg search Dictate

Name                               Repo                   Path                                    
----                               ----                   ----                                    
DragonDictate3.download.recipe     nmcspadden-recipes     DragonDictate3/DragonDictate3.download.recipe
DragonDictate3.munki.recipe        nmcspadden-recipes     DragonDictate3/DragonDictate3.munki.recipe
```

**Comment by arubdesu** [comment]
Did you make these with RecipeRobot? If you're looking for how to use the CodeSignatureVerifier processor properly, please consult https://github.com/autopkg/autopkg/wiki/Using-CodeSignatureVerification

**Comment by workflowsguy** [comment]
Yes, I created them myself with Recipe Robot.

@gregneagle: I am aware of the recipe for Dragon Dictate 3. This software version is no longer current (most recent release is 5, but I am still using version 4). Also, it does not have a CodeSignatureVerifier step.

@arubdesu: Thanks for the link, but I did not ask how to use the processor. I asked what this (for me)  nondescript error message means. I do not know what a "glob" is, but I have a suspicion that the CodeSignatureVerifier processor is not able to handle file/path names that have spaces in them.

Could you please confirm or deny this?

Thanks!

**Comment by arubdesu** [comment]
Hey @workflowsguy, please put the recipes you created in a gist if you would like help with them. This repo's issues is not a great place for general usage questions - you could join us in [MacAdmins Slack](macadamias.org), or post to [the mailing list](http://groups.google.com/group/autopkg-discuss). 
Perhaps you weren't expecting to need to know how to troubleshoot software, or anything about python in order to use autopkg or generate your own recipes, but I can't really tell you something you should research for yourself: glob is really commonly used, and while you don't need to understand it to solve your problem, we're not necessarily great at teaching you about general things. (And again, here's not the best place.)
That being said, here's an example of what `glob` is, specifically answering the question about paths when called from python:
``` python
$ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import glob
>>> glob.glob("/tmp/here's A path/*")
["/tmp/here's A path/and another one", "/tmp/here's A path/testy mc testers"]
```
I only needed to use double-quotes because of the single apostrophe in `here's`.

Here's where the error you ran into was generated by the code: [link](https://github.com/autopkg/autopkg/blob/868fb4fb0375ac5e6f460ef4fa3f5ffc60f19411/Code/autopkglib/CodeSignatureVerifier.py#L242) 
[Here's](https://github.com/autopkg/keeleysam-recipes/blob/master/CarbonCopyCloner/CarbonCopyCloner.download.recipe) another recipe for an app that has a space in its name and uses CodeSignatureVerification, and its output:

``` python
CodeSignatureVerifier
CodeSignatureVerifier: Verifying application bundle signature...
CodeSignatureVerifier: /Users/abanks/Library/AutoPkg/Cache/com.github.keeleysam.recipes.CarbonCopyCloner.download/downloads/Applications/Carbon Copy Cloner.app: valid on disk
CodeSignatureVerifier: /Users/abanks/Library/AutoPkg/Cache/com.github.keeleysam.recipes.CarbonCopyCloner.download/downloads/Applications/Carbon Copy Cloner.app: satisfies its Designated Requirement
CodeSignatureVerifier: /Users/abanks/Library/AutoPkg/Cache/com.github.keeleysam.recipes.CarbonCopyCloner.download/downloads/Applications/Carbon Copy Cloner.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
```
So, the code does seem to be telling you the truth - something about how that app was downloaded makes glob not like it, and until we can replicate your issue or you can figure out why, we're a bit stuck.

**Comment by nmcspadden** [comment]
Without any other details, the URL provided in your post downloads a zip that contains a signed flat package installer.  There's no need to extract the package here if your primary goal is to install it.  You can use code signature verification on the package itself:
```
$ pkgutil --check-signature ~/Downloads/Dragon\ Dictate\ Deutsch.pkg
Package "Dragon Dictate Deutsch.pkg":
   Status: signed by a certificate trusted by Mac OS X
   Certificate Chain:
    1. Developer ID Installer: Nuance Communications
       SHA1 fingerprint: F5 2E 23 08 F6 AE 3E AF 6C 9E 67 FD BB 4E 2F 35 73 5F 15 B3
       -----------------------------------------------------------------------------
    2. Developer ID Certification Authority
       SHA1 fingerprint: 3B 16 6C 3B 7D C4 B7 51 C9 FE 2A FA B9 13 56 41 E3 88 E1 86
       -----------------------------------------------------------------------------
    3. Apple Root CA
       SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60
```

My guess is that you passed in `requirement` to CodeSignatureVerifier, which is used to check apps, rather than `expected_authority_names`, which is suited to check packages.  It tried to find an .app in your unpack location, and failed, because there isn't one - there's only a .pkg.

**Comment by workflowsguy** [comment]
@nmcspadden Thank you for taking the time to look into this, I greatly appreciate it.
I was now able to correct the download recipe and get it to work.

The question is, could such an error be caught or an error message be shown that more clearly describes what the actual problem is?

**Comment by arubdesu** [comment]
It totally could, and would be most expedient if you did it and let us know how you did it, or even better sent a pull request. Right now all we know is that it didn't work for you at some point, you haven't showed us the recipe you started with, or how you fixed it. You can feed lots of invalid data to any tool that uses input files, only a portion of which can we account for and provide appropriate feedback.
