### ISSUE TITLE
CodeSignatureVerifier only respects last input_path specified.

### ISSUE THREAD

**Issue by erikng** [autopkg/autopkg#293]
When attempting to pass multiple arguments to CodeSignatureVerifier, only the last input_path is respected. To workaround this, you must have two CodeSignatureVerifier Processes, which results in some slowdown on the run and unmounting/remounting the dmg for each pass.

**Comment by gregneagle** [comment]
I don't really see this as a problem that needs to be addressed. The vast majority of recipes that do code signature verification only need to verify a single item; increasing the complexity of the CodeSignatureVerifier processor so it could support multiple items to verify and multiple requirements to check (and would also need to accurately map each set of requirements to each item) doesn't seem worth the effort. Doing this in a way that remained backwards compatible and also not confusing seems even harder.

Can you provide evidence to persuade me otherwise?

**Comment by erikng** [comment]
No. You are corrent that not many applications do this. Off the top of my head, I can only think of two.
