### ISSUE TITLE
SparkleUpdateInfoProvider fails on character encoding

### ISSUE THREAD

**Issue by workflowsguy** [autopkg/autopkg#294]
I have created an override for io.github.hjuutilainen.munki.Dash3 to get the description for the current release for Dash from it's Sparkle feed.

When running this recipe, "Autopkg run -vv" gives the following error:

SparkleUpdateInfoProvider
{'Input': {'appcast_url': u'https://kapeli.com/Dash3.xml',
           'pkginfo_keys_to_copy_from_sparkle_feed': (
    description
)}}

SparkleUpdateInfoProvider: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
SparkleUpdateInfoProvider: Version retrieved from appcast: 222
SparkleUpdateInfoProvider: User-facing version retrieved from appcast: 3.3.0
'ascii' codec can't encode character u'\u2022' in position 140: ordinal not in range(128)

Failed.

('\u2022' is the Unicode "bullet" character.)

**Comment by timsutton** [comment]
The issue appears to be that we're attempting to decode Unicode as ASCII and aren't doing any specific error handling.

It looks like SparkleUpdateInfoProvider has had this `decode()` on this since [the beginning](https://github.com/autopkg/autopkg/blob/0f435688126f20c3ddf83791300e6d7ccc869e38/Code/autopkglib/SparkleUpdateInfoProvider.py#L167). Your particular case seems to be resolved if I remove this `decode()`, and I'm not sure there's a reason why we should be decoding it in the first place.

If the description contains unicode characters and we don't attempt to decode them, SparkleUpdateInfoProvider passes them through to `pkginfo` and they arrive on disk intact. As far as I can tell these don't cause issues with `makecatalogs`, including running `makecatalogs` on Linux where FoundationPlist isn't available.

So I _think_ the solution here is to simply remove the `decode()`, however I'd love to get a second opinion.

Unrelated, the processor's behaviour of adding `<html><body>` and closing tags by default when retrieving a description included inline to the Sparkle feed is not the correct behaviour here, since those tags are already present. My guess would be that when I first implemented this option to process the `description` elements, the limited sample set of Sparkle feeds I used seemed to suggest this would be a good idea, when in reality Sparkle probably handles either case.

**Comment by workflowsguy** [comment]
While I can not comment on the consequences of removing `decode()`, I offer my help of testing any modifications you would make. I have recipes for various applications where I would like to use the release notes from the feed but in many cases currently cannot.

Also, enhancing the Processor to deal more of the Sparkle tags would be great. For this, I will create a separate issue.
