### ISSUE TITLE
Please add/fork my repo

### ISSUE THREAD

**Issue by apettinen** [autopkg/autopkg#317]
Couple of new recipes, Carthage and Corectl, plus install recipe for TextMate2 and OracleJava8.

https://github.com/apettinen/autopkg-recipes/tree/master

**Comment by timsutton** [comment]
Done and available here: https://github.com/autopkg/apettinen-recipes

Just one comment about the munki recipes: you'll probably want to put `pkginfo` into the `Input` section at the top of the recipe rather than including your pkginfo data inline as a Processor argument. This way people can easily override the initial pkginfo to add or change additional keys. When it's inline, they can only override the particular strings you've put substitutions in for.

**Comment by apettinen** [comment]
Ah, that's absolutely true, how stupid of me. :) Will fix.
