### ISSUE TITLE
please add/fork repo

### ISSUE THREAD

**Issue by jeremylarose** [autopkg/autopkg#332]
https://github.com/jeremylarose/autopkg-recipes

currently includes Horos, Duplicati, and QSyncthingTray

 .... would like to add Syncthing, UrBackup Client, and OpenShot Video Editor in the future

**Comment by timsutton** [comment]
For Duplicate and Horos, is there a reason the download URLs have to be hardcoded?

**Comment by jeremylarose** [comment]
I will fix these to be dynamic

**Comment by jeremylarose** [comment]
all recipes have been updated, tested, working, and will auto update, so not hardcoded anymore... Horos, Duplicati, QSyncthingTray, RemotixQC, OpenShot, Syncthing, and SyncthingInotify

**Comment by timsutton** [comment]
Sorry for the delay getting back to these. Took a look, and have a couple comments:

* Most of your MonoFramework recipes seem to exist already autopkg-org repos
* Some of your Windows recipes also seem to exist already in hansen-m
* Have you considered consolidating your sets of Windows drivers into more "generic" recipes so that you could avoid needing to have so many? For example, in cases where scrape or download URLs are just substituting in different Input variables?

We don't really have any established practices for handling Windows recipes, except that so far people have named them like "Product-Win.download.recipe".

**Comment by jeremylarose** [comment]
Ok, thanks, I will look into all of these.  I was avoiding the hansen-m recipes because they require other software to be installed on the system to work properly (which alot of people don't want to do) and was looking to keep them more simple and out-of-the-box working for autopkg newbies and not scare them away with added complexity.  As a far as the windows drivers goes, I see what your getting at.  Although, with windows you can't have something like a DellDriversPack because it would be too massive and you wouldn't want to deploy that to every machine.  I suppose there could be one recipe to download all the drivers and an extra Processor could be created to create individual packages out of all the downloads.... something like "Win.DellDriverPacks" ... and then a shared processor... MultiPkgCreator7z or something.  I will look into this more.
