### ISSUE TITLE
another repo

### ISSUE THREAD

**Issue by Tecnico1931** [autopkg/autopkg#333]
adding pritunl client 
https://github.com/Tecnico1931/Tecnico1931-recipes

**Comment by timsutton** [comment]
I'd recommend not using hyphens as the `NAME` here, particularly for the Munki recipe, since it has the potential to lead to ambiguous behaviour when such a name is listed in a client manifest. The general convention with AutoPkg recipes thus far has been usually to just drop the space, i.e. `PritunlClient` (or `PritunlClientElectron` if that's significant)

**Comment by Tecnico1931** [comment]
@timsutton updated to PritunlClient

**Comment by timsutton** [comment]
Sorry for the long delay on this. Should be available to push to here:

https://github.com/autopkg/Tecnico1931-recipes
