### ISSUE TITLE
Idea of blocking copied keys in MunkiPkginfoMerger

### ISSUE THREAD

**Issue by timsutton** [autopkg/autopkg#351]
For more complicated recipes which are able to fetch product metadata (like MSOffice, and the in-development mosen/ccp-recipes), right now we usually process this metadata using Feed processors and then either add them directly to `additional_pkginfo` or output them as their own named output variables.

Usually this means the recipe needs to hardcode this logic of substituting in items like `description`, for example, or potentially other keys. Similar issue as described in https://github.com/autopkg/recipes/issues/206. It's possible that certain keys probably should always be handled automatically in order for the pkginfo to work properly, but `description` is one where different environments may prefer one or the other.

I'm thinking another way to handle this would be for `MunkiPkginfoMerger` to support a global input variable that would typically be defined in one's override, which would be an array of keys that the admin wishes to be _not_ merged in by the processor. For example:

```plist
<key>Input</key>
<dict>
    <key>MUNKI_PKGINFO_KEEP_KEYS</key>
    <array>
        <string>description</string>
    </array>
</dict>
```

Then whenever `MunkiPkginfoMerger` is called to merge anything in from `additional_pkginfo`, it would skip updating any keys defined in the `MUNKI_PKGINFO_KEEP_KEYS` list. Not sure I like this variable name that much, but just throwing the idea out there.

**Comment by gregneagle** [comment]
This strikes me as overly complex. Every key in additional_pkginfo should simply override any identical key in pkginfo, which is the current behavior I think.

The issue here is this: 

1.  We define override variables at the _start_ of a recipe: pkginfo might be one. 
2.  A processor like the MSOffice2011UpdateInfoProvider outputs additional\_pkginfo
3.  MunkiPkgMerger merges additional\_pkginfo into pkginfo, with the result that keys in additional\_pkginfo override those in pkginfo, as expected, but with less-than-desired results.

If the merge went the other way, we'd be fine. If:

1.   We define override variables at the _start_ of a recipe and _additional\_pkginfo_ was one,
2.  MSOffice2011UpdateInfoProvider outputs _pkginfo_
3.  MunkiPkgMerger merges additional\_pkginfo into pkginfo, with the result that keys in additional_pkginfo override those in pkginfo, as expected, and with the desired results.

It would be difficult/near impossible to make a change like this without breaking every existing recipe override, but it would be cleaner and simpler.

Another possibility might be an additional input variable to MunkiPkgMerger that defines the "precedence" of the merge: set one way, additional\_pkginfo is merged into pkginfo; set another way pkginfo is merged into additional\_pkginfo (and then copied/renamed to pkginfo on output). This is more complex and possibly confusing, but could be implemented without breaking existing overrides, and would be simpler (IMO) than an array of keys to "keep".
