### ISSUE TITLE
MunkiImporter copy process shutil.copy very slow

### ISSUE THREAD

**Issue by tcinbis** [autopkg/autopkg#356]
The MunkiImporter is realy slow, when copying files >1GB.It seems like it is not a Munki problem, but an upstream library that causes the slowness. We can reproduce the slow copying proces when using shutil.copy in an isolated environment.
Is there any alternative to speed up the importing of bigger packages. 
We measured cp speed of ~18MB/s an shutil.copy writes with ~1.2MB/s.

**Comment by timsutton** [comment]
Is your repo SMB? Which version of macOS are you using to connect to your repo?

For what it's worth, I noticed slow copy speeds with `shutil.copy()` for quite a while as well, and I don't know what changed in recent Sierra versions, but it's massively improved in the past 4 months or so, to about a magnitude of what you're describing between `cp` and `shutil`.

**Comment by tcinbis** [comment]
Yes the repo is mounted via SMB and I am currently running 10.11.6

**Comment by timsutton** [comment]
Thanks for confirming, glad it's not something isolated to my environment. (Samba on Linux)

I looked at this issue quite a while ago and saw that switching from shutil to cp could have potentially introduced other issues, so I shelved the idea - and with it now seeming to have improved dramatically, seems less in need of being looked at.

MunkiImporter is in need of some updating for supporting Munki 3's [repo plugin](https://github.com/munki/munki/wiki/Repo-Plugins) system anyway, so that would almost certainly change some underlying repo-copy behaviour here.
