### ISSUE TITLE
Request to add a repo

### ISSUE THREAD

**Issue by Chalcahuite** [autopkg/autopkg#364]
Any chance of adding my repo to the main autopkg list? https://github.com/chalcahuite/chalcahuite-recipes.git

**Comment by timsutton** [comment]
Thanks for submitting these, and apologies for the delay adding the repo. It's now available here:

https://github.com/autopkg/chalcahuite-recipes

One note you may want to add in the future is for dependencies:

* Outset recipe depends on grahamgilbert-recipes and patgmac-recipes
* dockutil on jessepeterson-recipes
* Push Diagnostics on nmcspadden-recipes

Since AutoPkg currently doesn't automatically clone any dependent repos for parent recipes, you may want to include these repos in documentation, using the repo's README and/or the recipe's Description field. The latter is probably preferable as it's visible to `autopkg` directly.
