### ISSUE TITLE
Please fork my repo

### ISSUE THREAD

**Issue by aschwanb** [autopkg/autopkg#376]
https://github.com/ITS-Unibas/autopkg-recipes

A repo with recipes for mainly edu focused software maintained by the IT services at the university of Basel.

If possible, we would like to keep using this repo as a team and update/add recipes we need. Could you name the repo `its-unibas-recipes` to reflect this.

Thank you very much.

**Comment by hjuutilainen** [comment]
Thank you for these. I'll fork this soon but I have a couple of notes and minor nitpicks for the recipes:

- Cleanup whitespace to be consistent (use either tabs or spaces). This will make the recipes easier to read when viewing in browser.
- In download recipes, put EndOfCheckPhase processor right after the URLDownloader etc. and before any extraction or signature verification. This will speed up running autopkg in check mode since it doesn't need to extract and verify if nothing has changed.
- In Karabiner.download, I would personally move the Versioner and MunkiInstallsItemsCreator to the Munki recipe. I would also check the signature of the installer package only and not extract the package at all.
- Does F5Transkript.download really need a custom processor to get the download URL? You can of course use a custom processor but in this case I think you could use URLTextSearcher to extract the needed bits from the download page.

**Comment by aschwanb** [comment]
Hey @hjuutilainen 

I updated the recipes according to your suggestions but I think we need to keep the custom processor for F5Transkript.download. The reason for it is that we get an escaped URL from the download page.

We basically need is a way to string replace from `&amp;` to `&`. But I don't know if this could be done with URLDownloader or URLTextSearcher. Do you know if this could be done with the current processors?

**Comment by aschwanb** [comment]
Update: I opened a pull request with the proposed change. See #380

**Comment by hjuutilainen** [comment]
I think we've had a few discussions about unescaping URLs before but if I recall it correctly there were always other issues caused by this. Let's discuss this more in #380.

For the F5Transkript.download recipe, you could use a single URLTextSearcher to capture multiple strings (with Python RE named groups) and then compose the download URL from the pieces but it's not pretty:

```
<dict>
	<key>Processor</key>
	<string>URLTextSearcher</string>
	<key>Arguments</key>
	<dict>
		<key>url</key>
		<string>https://www.audiotranskription.de/downloads.html</string>
		<key>re_pattern</key>
		<string>downloadfile.php\?k=(?P&lt;k&gt;\d+).+d=(?P&lt;d&gt;\d+).+l=(?P&lt;l&gt;[a-z]+).+c=(?P&lt;c&gt;[\da-z]+)"&gt;Download.*Mac&lt;/a&gt;</string>
	</dict>
</dict>
<dict>
	<key>Processor</key>
	<string>URLDownloader</string>
	<key>Arguments</key>
	<dict>
		<key>url</key>
		<string>https://www.audiotranskription.de/audot/downloadfile.php?k=%k%&amp;d=%d%&amp;l=%l%&amp;c=%c%</string>
		<key>filename</key>
		<string>f5.zip</string>
	</dict>
</dict>
```

You can of course continue with a custom processor, that's why they're supported. It's just my personal preference to try to minimise custom processor usage where possible to keep recipes simpler for the end user and easier to audit. We'll create a recipe repo fork for you in any case :)

**Comment by aschwanb** [comment]
I'm with you on the usage of custom processors. Their usage should be limited to special cases - and unescaping an url should arguably not be one of these.

I'll keep the the processor for the moment but hopefully not for long. We'll see how #380 goes :-)

**Comment by aschwanb** [comment]
After thinking about this some more I would like too stick to the custom url provider. While I agree that your solution is very elegant, I think using a custom processor adds a bit of readability.

I updated the other recipes according to your suggestions.

Do you think we can fork the repo now?

**Comment by hjuutilainen** [comment]
This is now available here: https://github.com/autopkg/its-unibas-recipes

Let me know once you've accepted the invitation and I'll change your access level to owner.

**Comment by aschwanb** [comment]
Accepted the invitation. Thank you very much!

**Comment by aschwanb** [comment]
@hjuutilainen could you also add @tcinbis to the repo.

Thank you

**Comment by hjuutilainen** [comment]
@tcinbis invited.

**Comment by tcinbis** [comment]
@hjuutilainen thanks!

**Comment by aschwanb** [comment]
Thank you very much @hjuutilainen
