### ISSUE TITLE
Why does autopkg runs with /usr/bin/python ?

### ISSUE THREAD

**Issue by tcinbis** [autopkg/autopkg#405]
Hey there!
We recently wanted to use the `defusedxml` python module for a processor, but discovered, that it is not included in the `/usr/bin/python` version shipped by Apple. 
If you would change the header of the autopkg executable to `#!/usr/bin/env python` it would be able to use "more modules".

So my question is, why is autopkg using `/usr/bin/python` instead of `/usr/bin/env python` and is it worth changing it to be able to use a more secure xml parser for different Processors? What is the advantage of using `/usr/bin/python`?

Thank you very much in advance!

**Comment by arubdesu** [comment]
Hi Tom,
I'd think the reason is Apple's python is compiled with the bindings needed to leverage pyObjC, so every instance you see of `import Foundation` or CoreFoundation would rely on that. In fact, there's been commits that made sure the shebang didn't magically inherit its env, not that it wouldn't be useful for what you want. If you'd like to make your own custom processor I imagine you could choose whatever shebang would work for you. (There's no great docs for that yet, but more background is mentioned here: https://github.com/autopkg/autopkg/wiki/Recipe-Writing-Guidelines)

**Comment by tcinbis** [comment]
Hi @arubdesu ,
thank you for your answer!

Unfortunately it seems like the shebang from my processor is ignored or overwritten (I don't know).  I already tried to use`#!/usr/bin/env python` in my processor, but still no luck.

But I now understand why it is needed to use Apple's python. Thanks

**Comment by gregneagle** [comment]
You certainly don’t have to install and use your own version of Python to use third-party Python modules...
