### ISSUE TITLE
URLDownloader Feature Request: Assign filename from redirected URL, not original one

### ISSUE THREAD

**Issue by jazzace** [autopkg/autopkg#432]
I found this specifically when working with the Microsoft Office recipes that download full installers (@arubdesu, @rtrouton). If you use Microsoft's FWLink URLs (e.g., https://go.microsoft.com/fwlink/?linkid=871748), they redirect to the current URL by returning a HTTP/1.1 302 status. AutoPkg correctly parses that, gets the new URL, and downloads the correct item. Based on the code on Line 139 of URLDownloader, the download is assigned the name of whatever is after the final slash in the original URL (in my example, `?linkid=871748`).

If you enter the same URL in a web browser, the resulting download is named in a more expected manner, that is, it uses the filename being downloaded (which is equivalent to what is after the final slash in the resolved/final URL, which in the above example is `Microsoft_Word_16.16.18091001_Installer.pkg`).

In the case where URLDownloader picks up a new URL due to a 301, 302, or 303 redirect (Lines 250-256), it would better match user expectations (and could potentially be more useful) if the output filename was changed to what the final URL provides. Perhaps this is something that could be considered if/when the URLGetter class suggested in Issue #416 is developed.

**Comment by MichalMMac** [comment]
Look at my refactor branch here https://github.com/MichalMMac/autopkg/tree/curlrefactor

This issue is covered in this commit https://github.com/MichalMMac/autopkg/commit/b90d04f627d5f04de3b1f598de2dc4ff17f61d21.

Feel free to test my refactoring attempt and discuss in autopkg google [group](https://groups.google.com/forum/#!topic/autopkg-discuss/i4FswIat6GA).

**Comment by n8felton** [comment]
I believe this is also covered in #254.

**Comment by MichalMMac** [comment]
I added `rename_after_redirect` switch set to `False` by default making this functionality optional. https://github.com/MichalMMac/autopkg/commit/88d5232f001bf07d12857faf43da9962ba60e20e

**Comment by MichalMMac** [comment]
It's not as simple as I though. My previous solution broke etag checking. Since renamed filename is not known before download it was downloaded every time.

Updated solution https://github.com/MichalMMac/autopkg/commit/c0024278099cf3841a776c9005a7426ca0df9802 :

1. Downloads the file last part 
2. Names it with last part of `url` variable or `filename` variable (when set)
3. Instead of just renaming it to filename discovered from Location HTTP header it creates a hard link.

Only alternative to hardlink I can think of would be storing and loading filename from some special text/plist file just for this purpose.

**Comment by nmcspadden** [comment]
Is this issue still present in either master, or the new urlgetter branch?

**Comment by MichalMMac** [comment]
I did not implement this in newurlgetter branch. I am willing to work on this after newurlgetter is merged into master. There are multiple way to solve this.

**Comment by nmcspadden** [comment]
The hard link is a clever solution, and I like that approach, but I do slightly worry that it would be confusing to someone looking at their Cache folder and being unclear on why they have what appears to be two identical downloads. I'm also not entirely sure what APFS will show for the drive space usage. 

However, the likelihood that most people spend a lot of time looking in their caches is pretty low. 

I'm also not really opposed to storing data persistently across runs, but if we're going to do that, we should come up with a standard schema that all processors could choose to implement.

**Comment by MichalMMac** [comment]
I am thinking about the third option. 

Use `curl` with `--head` option before the actual download to get filename from `Location`, `Content-Disposition` or other header.

**Comment by MichalMMac** [comment]
I implemented my idea in #571 Please take a look.

**Comment by MichalMMac** [comment]
@jazzace @n8felton Hi there. Could you test new `prefetch_filename` option in `URLDownloader` (1.4 or 2.0b3)? Does it solve the problem for you? I'll take any comments/improvement ideas.

**Comment by jazzace** [comment]
Ran a quick test using Microsoft Word and it works as expected. Thanks. For recipe debugging purposes, I would like to see you put a line in the verbose output (level 2 or 3) that states what value you have retrieved for the filename.

Also, there were some formatting and spelling errors in the processor info description. I'm going to try a short rewrite of that and do a pull request.

**Comment by MichalMMac** [comment]
Since Debug output is now merged I believe this issue can be closed. @jazzace @nmcspadden
