### ISSUE TITLE
Question: Differing behavior with file ownership. pkgbuild vs PkgCreator

### ISSUE THREAD

**Issue by JaySoyer** [autopkg/autopkg#444]
**Giving:** 

- package which places a file `myLA.plist` in `/Library/LaunchAgents/`
- Prior to creating the package, the file `myLA.plist` has **jaysoyer/awesome users** owner/group

**Using CLI `pkgbuild`**
- At install time the file is placed with the appropriate **root/wheel** owner/group.
- Using **Suspicious Package**, it appears the file ownership change happens automatically when packaged and not when installed.

**Using Processor `PkgCreator`**
- At install time the file is placed with a random owner/group ID number.  Eg, **93412/24234** which does not correlate to the correct IDs of **jaysoyer/awesome users**
- Using **Suspicious Package**, it appears the file ownership change did not happen.
- So I'm guessing at install time, the installation doesn't know about my **jaysoyer/awesome users** ID/Groups so it just randomly creates new ones?  Hence the random IDs.

**This leads to my question:**
Why is this happening?  

Under the hood it _looks_ like `pkgbuild` is being invoked.  

As a resolution, I've noticed recipes simply pass in the `chown` command -> [Example](https://github.com/autopkg/recipes/blob/master/AutoPkg/AutoPkgGitMaster.pkg.recipe#L255-L303).
Which can be very tedious for those packages that need to copy over a ton of files.  Sure I can set **root/wheel**  ownership prior to packaging but that makes developing the recipes a pain.  Is there not a better way to address this?

I haven't tested with an ***.app** going into `/Applications` yet.  I'm afraid to see the same behavior.

**Comment by gregneagle** [comment]
This issues site is not really intended as a general support/discussion site, which is why your issue has been left untouched. The autopkg-discuss list is a better place for this type of discussion.

As for "why does this happen?" the answer is here:

https://github.com/autopkg/autopkg/blob/master/Code/autopkgserver/packager.py#L469

`--ownership preserve` is more flexible/enables more fine-grained control than the `pkgbuild` default of `--ownership recommended` but yes, requires you to specify the desired owner, group and mode of files. Do note that the `chown` option is recursive:

https://github.com/autopkg/autopkg/blob/master/Code/autopkgserver/packager.py#L377-L391

**Comment by JaySoyer** [comment]
Thanx for the reply. I was not aware of the `--ownership` flags for `pkgbuild`.  Good intel!
