### ISSUE TITLE
Recipes fail in Processor: DmgCreator

### ISSUE THREAD

**Issue by workflowsguy** [autopkg/autopkg#455]
On my system, all recipes that used to work previously now fail with the same type of error message like this one:

```
The following recipes failed:
    DEVONsphereExpress.munki
        Error in local.munki.DEVONsphereExpress: Processor: DmgCreator: Error: creation of /Users/guy/Library/AutoPkg/Cache/local.munki.DEVONsphereExpress/DEVONsphere Express.dmg failed: hdiutil: hdiutil: create failed - No child processes

Nothing downloaded, packaged or imported.
```

I suspect that this is related to Issue #454, but I don't know how to debug/verify this.

**Comment by gregneagle** [comment]
since these used to work on your system and now do not, this isn't due to _autopkg_, which has not changed in quite a long time, but rather due to a change on your local system.

This issues tracker is not really intended as a support mechanism. For that, please post in the autopkg-discuss group: http://groups.google.com/group/autopkg-discuss

Closing this. Feel free to reopen or open a new issue if there are actionable autopkg code issues.

**Comment by workflowsguy** [comment]
For a solution, see my comment for #454
