### ISSUE TITLE
SparkleUpdateInfoProvider fails on valid Sparkle feed

### ISSUE THREAD

**Issue by workflowsguy** [autopkg/autopkg#461]
According to [https://validator.w3.org/feed/](url), [https://www.houdah.com/houdahSpot/updates/cast5.xml](url) is a valid feed.

Yet SparkleUpdateInfoProvider in Autopg 1.0.4 fails, giving just the message

`SparkleUpdateInfoProvider
{'Input': {'appcast_url': u'https://www.houdah.com/houdahSpot/updates/cast5.xml'}}
SparkleUpdateInfoProvider: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
Error parsing XML from appcast feed.
Failed.
`

**Comment by gregneagle** [comment]
`curl https://www.houdah.com/houdahSpot/updates/cast4.xml` does not return anything that looks like valid XML to me.

In any case, this does not yet appear an issue with _autopkg_. It _might_ be an issue with the HoudahSpot.download recipe. I'd suggest opening an  issue at https://github.com/autopkg/homebysix-recipes/issues

**Comment by gregneagle** [comment]
(as a side note, I can get a valid XML document if I do `curl --compressed https://www.houdah.com/houdahSpot/updates/cast4.xml` so I'm betting they are not returning the correct mime-type on their response, and curl doesn't know it is compressed (until I tell it it is)

**Comment by gregneagle** [comment]
...on further investigation, this actually looks like a bit of a curl bug (or missing feature) and a bit of a website bug and there's no easy way for a recipe to work around it. This might indeed require a change to SparkleUpdateInfoProvider.

**Comment by gregneagle** [comment]
See https://stackoverflow.com/questions/8364640/how-to-properly-handle-a-gzipped-page-when-using-curl

There are two problems:
1) The website returns a gzipped response even those curl did not say that was acceptable. (using the "Accept-Encoding: gzip" header in the request). It should not do that.
2) curl doesn't pay any attention to the content-encoding header in the response unless you use the --compressed flag.

The fix is to use the `--compressed` option with `curl`. Some testing needed to see if adding that option breaks anything (I believe it won't)

**Comment by gregneagle** [comment]
Addressed here: https://github.com/autopkg/autopkg/commit/605b8a81a356ee81b9b050d7e447659c2a626665
