### ISSUE TITLE
Fork recipe repo

### ISSUE THREAD

**Issue by ewancolyer** [autopkg/autopkg#630]
Hey! Can my repo be forked please!

https://github.com/ewancolyer/ewanc-autopkg

Thanks,

Ewan

**Comment by homebysix** [comment]
Hi @ewancolyer - It looks like some of your recipes use the identifier prefix `com.github.ewancolyer1`, while others use `com.github.ewancolyer`. Is this intentional?

Just double checking, because after the recipes are public and being used by others, it's discouraged to change their identifiers.

**Comment by homebysix** [comment]
Also, there are two recipes in your repo that appear to duplicate existing recipe functionality. While duplicates aren't uncommon, we discourage duplication unless it's for a specific reason.
- SFSymbols.munki
- SFSymbols.download

And these recipes aren't running successfully for me at the moment:
- SF Symbols/SF Symbols.download.recipe
- NewTek, Inc./NewTekNDITools.download.recipe
- Editshare LLC/EditShare Connect.download.recipe
- SimpleHelp Ltd/SimpleHelp Technician.download.recipe

**Comment by ewancolyer** [comment]
Thanks for taking the time to have a look :)

Ive swapped out the `ewancolyer1`'s for `ewancolyer` it was from when my github account was ewancolyer1, and I decided to update the identifier with it... just not on all the recipes for some reason :)

Both SimpleHelp and EditShare require the user to enter their domain for their instances as the packages are hosted on your instance of the product, I have added the `StopProcessingIf` processor for those 2 download recipes now.

The duplicates have been removed along with NewTek which was broken and unused.

**Comment by homebysix** [comment]
Thank you for addressing those items.

I also see there are a few recipes that duplicate the functionality of existing recipes in the org. [We discourage](https://github.com/autopkg/autopkg/wiki/Sharing-Recipes#repo-maintenance-expectations) this kind of redundancy unless it's for a good reason, and that reason should be outlined in the recipe's description.

- AdobeCreativeCloudInstaller.munki.recipe
- GarminExpress.download.recipe
- GarminExpress.pkg.recipe
- NordVPN.download.recipe

Since it looks like you're using Recipe Robot for building these recipes, [check out this video](https://youtu.be/5VKDzY8bBxI?t=2829) for a walkthrough on building child recipes for existing parents. This will enable you to remove the redundant download and pkg recipes above.

**Comment by homebysix** [comment]
Hi @ewancolyer - Are you still working on cleaning up the redundant recipes above? I can do another review when you're ready.

**Comment by ewancolyer** [comment]
Thanks for following up on this!

Not currently, I've moved jobs and are not currently using autopkg. I will try and address these issues when I get some free time :)
