### ISSUE TITLE
Add me back to my repo?

### ISSUE THREAD

**Issue by PeetMcK** [autopkg/autopkg#662]
So I converted my personal account (peetinc) into an organization. Which of course means I no longer have access to my recipe repo (peetinc-recipes). (You can see that I'm the owner of peetinc ... https://github.com/orgs/peetinc/people). 

Would you mind adding me back to the peetinc-recipes repo?

Cheers.Peet

**Comment by homebysix** [comment]
I had @PeetMcK change the membership to public, in order to verify he is the sole member of the converted org:

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/7801391/90272535-685e2780-de12-11ea-9927-a540ff23c0ae.png">

Added @PeetMcK to peetinc-recipes team, which should grant access to the repo.
