### ISSUE TITLE
add my repo please

### ISSUE THREAD

**Issue by pairjal** [autopkg/autopkg#675]
hello sir,

can add my repo please?
https://github.com/pairjal/pairjal-recipes

Thanks.

**Comment by arubdesu** [comment]
Hey there, thanks for sharing your work! Please consider three things:

- I'm sure you don't intend to offend, but this org is not all sirs/men, please don't use gendered pronouns when addressing several people (men are not the 'default')
- this is the only recipe in the repo, and relies on [autopkg/flywire-recipes](https://github.com/autopkg/flywire-recipes), it would perhaps be better to send @LcTrKiD a message asking if he wouldn't mind hosting the file alongside his other variants for this product to keep them all in one place. At the minimum you would want to instruct people that they'd need the parent recipes or they'd receive an error message.
- alternatively, you could try having this added to [autopkg/jss-recipes](https://github.com/autopkg/jss-recipes) by sending a pull request, since the one variant included is for Jamf

**Comment by MichalMMac** [comment]
> I'm sure you don't intend to offend, but this org is not all sirs/men,
@arubdesu Maintainers are.

**Comment by homebysix** [comment]
> alternatively, you could try having this added to autopkg/jss-recipes by sending a pull request, since the one variant included is for Jamf

This is a good suggestion, and would somewhat distribute the burden of maintaining the recipe.

@pairjal, do you have more recipes planned, or is TablePlus.jss the sole item you're looking to get shared?

**Comment by pairjal** [comment]
hi all,

okay maybe I try that pull request to jss-recipes..so will need to merge right
In future maybe I might have other recipes, but for now just TablePlus.jss

**Comment by homebysix** [comment]
Sounds good. You can find the [contribution instructions for jss-recipes here](https://github.com/autopkg/jss-recipes/blob/master/CONTRIBUTING.md).
