### ISSUE TITLE
Request for Add/fork our recipe repo

### ISSUE THREAD

**Issue by yourejuanito** [autopkg/autopkg#693]
Dear AutoPkg Team,

we have set up a Github repository with our own recipes: https://github.com/yourejuanito/yourejuanito-recipes

It would be great if you could fork this repo to make those recipes available to the AutoPkg community, as described in your Wiki.

Thanks in advance!
Juan and the MLSE Team

**Comment by homebysix** [comment]
Hi @yourejuanito - I found a few issues:

- It appears your com.github.yourejuanito.download.CiscoWebexMeetings recipe duplicates the function of com.github.dataJAR-recipes.download.CiscoWebexMeetings. [We discourage](https://github.com/autopkg/autopkg/wiki/Sharing-Recipes#repo-maintenance-expectations) this kind of redundancy unless it's for a good reason, and that reason should be outlined in the recipe's description.

- Your Cisco Webex Meetings.pkg.recipe should not be using the com.github.dataJAR-recipes identifier prefix.

- Please consider submitting your JSS type recipes to the jss-recipes repo instead of hosting them in your own repository, if your recipes' behavior is aligned with the [jss-recipes workflow](https://github.com/autopkg/jss-recipes#standard-workflow-for-jss-recipes).

- The file at __Office-Reset/Untitled-1__ looks like a script, but doesn't appear to be associated with the "Office Reset" product.

- Why does your Outlook Reset.download.recipe have URLTextSearcher and URLDownloader downloading the ClickShare product? I'm sure this was just an accident, but this kind of cross-product naming error is one way [bad things](https://www.youtube.com/watch?v=LnvQmLcDF8w) can happen.

- Why is the parent recipe for your ClickShare.jss.recipe set to com.github.autopkg.mikestechshop.pkg.Discord?

- What is __Cisco Webex Meetings/selfService_macOSUpdate.sh__ and what does it have to do with Cisco WebEx Meetings?

Some of the above are significant errors, so I am not going to fork this recipe repo at this time. If you address the errors and wish to have another shot, please reopen this issue.
