### ISSUE TITLE
Establish a Recipe Naming Convention Including CPU/OS?

### ISSUE THREAD

**Issue by jgstew** [autopkg/autopkg#728]
What should the naming convention be for recipes? Particularly as there are now non-MacOS recipes, but there are also non-Intel MacOS recipes.

Examples:

- https://github.com/autopkg/tallfunnyjew-recipes/blob/master/VLC-Intel-asap/VLC-Intel-asap.download.recipe
- https://github.com/autopkg/tallfunnyjew-recipes/blob/master/VLC-Arm-asap/VLC-Arm-asap.download.recipe

Before now, it was safe to assume if not otherwise specified that all recipes were for Intel based Macs, so that seems like a valid default assumption going forward. Same goes for if not otherwise specified, then it is assumed a recipe is a plist, but could be YAML as well going forward.

This means with being fully explicit then these would all be possible future recipes that could be valid and used concurrently:

VLC.download.recipe (implies intel mac and plist)
VLC.ARM.download.recipe (implies mac and plist, explicitly specifies ARM)
VLC.Mac.Intel.download.recipe.plist
VLC.Mac.ARM.download.recipe.plist
VLC.Win.Intel.download.recipe.plist
VLC.Win.ARM.download.recipe.plist
VLC.Mac.Intel.download.recipe.yaml
VLC.Mac.ARM.download.recipe.yaml
VLC.Win.Intel.download.recipe.yaml
VLC.Win.ARM.download.recipe.yaml

Just wondering if there should be a recommended naming convention standard to follow that includes optional CPU and OS info and what order and formatting that would take.

%software_name%.%os%.%CPU%.%recipe_type%.recipe.%recipe_file_format%

**Comment by nmcspadden** [comment]
If you are asking if we should be **prescriptive** about names:
I don't think it makes a lot of sense to rename/duplicate existing recipes, especially as more and more vendors produce universal builds. The main goal for most people is to get the latest version of X, and therefore splitting/renaming recipes would cause everyone's existing recipe lists to likely break or require a lot of admin effort. I don't think that's particularly worthwhile.

Ideally, the existing recipes would be updated to support universal builds. For apps that do not have universal builds (or won't any time soon), I would personally be more in favor of having the existing recipes point to the _newest_ releases (i.e. ARM builds, generally); if someone (in a PR, or if the owner themselves) wants to maintain a separate recipe for Intel-only, I think that should be up to the author and/or community.

As for what we do with macOS vs. non-macOS recipes, that's still to be determined, as non-macOS support is not officially available yet.

If you are suggesting we should **recommend a naming convention**:

I'm not opposed to adopting newer naming styles going forward, but we'd have to support both old and new formats for some time. 

Rather than rely on filename, I'd rather we specify recipe behavior based on already existing structural information - i.e. keys within a recipe. I think filenames are very suboptimal ways of keying critical information, and also they're not particularly accurate either - for example, we have .munki recipes that also the download portion, and it's entirely possible to make a .download recipe do more than just download. It's really convention, rather than hard rule. And based on the fact that it's mostly convention, I think keeping it as flexible as possible is the best approach.

**Comment by nmcspadden** [comment]
For the record, I'm not cutting off discussion on this topic - I'd love to have other people's thoughts. I'm just closing the issue because I am not (at the moment) treating this actionable.

**Comment by gregneagle** [comment]
Discussions might be better on the autopkg-discuss list.

**Comment by jgstew** [comment]
@nmcspadden 

To be clear, I'm not suggesting prescriptive names only recommendations.

I also don't think existing recipes should be renamed. I definitely don't think that would be valuable.

I am just suggesting that having some guidance around naming convention would be useful. More like best practices.

I agree if universal binaries exist, then that is ideal, but those will probably become non-universal at some point in the future as well.

Also non-MacOS may not be officially supported for running AutoPkg but generating non-MacOS stuff with AutoPkg running on MacOS works just fine today, though it does take some extra effort to get info like version number from windows binaries that would be trivial to do on Windows natively.
