### ISSUE TITLE
new repo

### ISSUE THREAD

**Issue by anton-prymak** [autopkg/autopkg#759]
Please add my repo. 
It's being developed now and I going to add more recipes for other applications we use at SPS Commerce . 
If possible, name it spsc.
Thank you!
https://github.com/anton-prymak/spsc

**Comment by homebysix** [comment]
Hi @anton-prymak - A few questions:

- Would `spsc-recipes` be acceptable? That would follow the naming convention we've established.
- I see that `APP_FILENAME` is defined in many recipes, but is never used. Is there a reason for that?
- For your Microsoft product download recipes, what is the justification to add new recipes instead of using jazzace's [MicrosoftMacProductFWLink.download](https://github.com/autopkg/jazzace-recipes/blob/master/Microsoft/MicrosoftMacProductFWLink.download.recipe) or rtrouton's family of [Microsoft*365.download](https://github.com/autopkg/rtrouton-recipes/blob/master/MicrosoftWord365/MicrosoftWord365.download.recipe) recipes? A good primer on the options already available is [available here](https://maclabs.jazzace.ca/2019/05/18/office-autopkg-recipes-update.html). We discourage duplication of existing recipes whenever possible.
- What is the purpose of the `.history` folder in the repo? If this repo becomes public, these recipes will likely appear in search results.
- Your Word.download recipe is `com.git.spsc.download.word`, but you probably mean for it to be `com.github.spsc.download.word`.
- Your Zoom recipe downloads the consumer Zoom installer, rather than the [IT installer](https://support.zoom.us/hc/en-us/articles/115001799006-Mass-Deployment-with-Preconfigured-Settings-for-Mac). Existing recipes use the IT installer. This isn't duplication per se, but I'm interested in why you chose the consumer version?

**Comment by anton-prymak** [comment]
Hi @homebysix Thanks for the reply and your questions.

- Yes, please, spsc-recipes is acceptable. 
- It's going to be used to name output files to match our internal PKG naming conversion.
- Same reason, we need PKG files under our specific naming conversion.
- Deleted the folder and added .gitignore
-  Fixed, thanks!
- Thanks for the advice, it looks awesome. I'll review it with our AV team and fix it if they ok with that.

**Comment by gregneagle** [comment]
If these recipes are meant primarily to meet internal requirements and you haven’t given much thought to public use of them than I wonder why you want these added to the public repos.

**Comment by homebysix** [comment]
I agree with Greg. Most of your recipes seem to be an organization-specific flavor of existing recipes, and seem better suited to a repository (either public or private) owned and maintained by your company rather than one which is searchable within the AutoPkg org on GitHub.

If you've got a compelling reason for these recipes to be public, I'm open to it — but right now I'm leaning towards politely declining.

**Comment by arubdesu** [comment]
Pardon if I also add others can still use `autopkg search` with the -u flag and point at the github username/owner for your repo to discover it, and even repo-add it without it being under the autopkg org, just in case you weren't aware of that option.
