### ISSUE TITLE
Change default branch of grahampugh-recipes to "main"

### ISSUE THREAD

**Issue by grahampugh** [autopkg/autopkg#765]
**Describe the problem**
I wish to switch the default branch of autopkg/grahampugh-recipes to the "main" branch. It is currently set to the "master" branch. The option to do this ourselves is disabled.

I understand that I should not remove the "master" branch for a period of time, to give users of my repo time to update their repo caches. From discussion with @nmcspadden in the MacAdmins Slack `#autopkg` channel, AutoPkg should "do the right thing" when a `repo-update` command is run, though I of course cannot verify this.

A couple of other users have also stated they would like to move away from using "master".

**Comment by homebysix** [comment]
As discussed in Slack, I've changed the default branch to your existing `main` branch without deleting `master`.

People who have cloned your repo will probably be required to `repo-update` in order to smoothly transition to the new default remote branch. You'll need to keep `master` in place for a while to allow people to do that.

After a while, you can delete `master`, at which point people who haven't run `repo-update` will likely get this error: https://github.com/autopkg/autopkg/issues/751

This is the first repo we've attempted to transition smoothly (i.e. maintaining both branches for a while) — so the above theories are subject to correction once tested in the real world. I'm eager to hear whether this works well.

**Comment by grahampugh** [comment]
@homebysix it looks like `repo-update` does not change the branch from `master` to `main`. So it looks like people have to `repo-delete` and `repo-add`. 

Do you think the fact that `master` still exists prevents the default changing on clients, or that people would have to perform `repo-delete` and `repo-add` regardless (the difference just being that it wouldn't break immediately)? If the latter, then it may actually be better to delete `master`.  But either way, it's not ideal unfortunately.

**Comment by nmcspadden** [comment]
Oof, that's unfortunate. I was really hoping it would 'just work.' So there are two ways of looking at this:
1. If you delete 'master' while people still have it checked out, git throws errors when you interact with the local checkout in any way that involves contacting upstream, and thus AutoPkg basically skips it and doesn't include it in search patterns, but it doesn't really tell you this so Autopkg unfortunately breaks in a user-unfriendly way.
2. If you don't update the local repos to switch to a new branch, and you keep 'master' upstream, it seems git doesn't automatically switch people over. So AutoPkg doesn't break, but it doesn't update people's local repos.

This is something worth posting to autopkg-discuss - how should we handle this?

**Comment by nmcspadden** [comment]
The branch got changed to 'main' and... well, unfortunately, it broke. There's no way around this limitation - if the remote branch is deleted from github, all the git clones will cry when someone runs repo-update.

**Comment by homebysix** [comment]
I was pondering one way around the limitation — using the GitHub API to check the `default_branch` of the repo when a standard fetch/pull fails. (I'm planning to do something similar for [another project](https://github.com/homebysix/repo-lasso) of mine.) That's not a trivial feature add though.
