### ISSUE TITLE
Please add ljcacioppo-recipes

### ISSUE THREAD

**Issue by ljcacioppo** [autopkg/autopkg#772]
Can my repo please be forked. I plan to move additional recipes to them as I audit the ones I have written.

https://github.com/ljcacioppo/recipes.git

Thanks!

**Comment by homebysix** [comment]
Hi @ljcacioppo - I've created a repo for you here: https://github.com/autopkg/ljcacioppo-recipes

Curious: why build your own pkg recipe instead of using existing ones (for example, `com.rderewianko.pkg.DEPNotify`)? Not a major deal, but some of the differences could be PRs upstream.

Also, note that JSSImporter recipes may have an expiration date due to Jamf's upcoming authentication changes. See Graham's post [here](https://grahamrpugh.com/2022/02/16/jssimporter-jamf-pro-api-token-auth.html) for details.

**Comment by ljcacioppo** [comment]
@homebysix I forgot I had requested this. Thank you for getting it added, but unfortunately, it probably makes the most sense for the repo to be removed - sorry for the additional work.

Nearly all of these were only .jss recipes and I am transitioning to a new role where I don't believe I would be able to maintain new .jamf recipes for them

**Comment by homebysix** [comment]
No problem — I've removed the repo. Thanks for keeping things tidy!
