### ISSUE TITLE
Please fork my recipes

### ISSUE THREAD

**Issue by jby** [autopkg/autopkg#789]
I have a repo here: https://github.com/jby/autopkg_recipes

**Comment by homebysix** [comment]
Hi @jby - a couple questions before I create this repo:

- The recipes in the Objective-See folder won't be addressable by AutoPkg, since repositories are only searched 2 levels deep. Flattening the recipes one level up should fix this.
- The Objective-See recipes appear to duplicate the functions of those found elsewhere in the autopkg org. Duplicate recipes are discouraged in the autopkg org, so if your recipes do something different than the existing public recipes, I'd recommend adding some information to your recipes' descriptions detailing the differences (see [this example](https://github.com/autopkg/MLBZ521-recipes/blob/49c542915b1777ae3c2ffbf8a179cefb34d19299/NoMAD/NoMADLoginAD.jss.recipe#L5-L8)). Otherwise, see if you can use existing recipes as parents for any new ones. List of existing recipes is below:
    - `apizz-recipes/BlockBlock/BlockBlock.pkg.recipe`
    - `apizz-recipes/BlockBlock/BlockBlock.munki.recipe`
    - `zentral-recipes/BlockBlock/BlockBlock.download.recipe`
    - `ahousseini-recipes/KnockKnock/KnockKnock.pkg.recipe`
    - `ahousseini-recipes/KnockKnock/KnockKnock.download.recipe`
    - `andrewvalentine-recipes/KnockKnock/KnockKnock.install.recipe`
    - `andrewvalentine-recipes/KnockKnock/KnockKnock.pkg.recipe`
    - `andrewvalentine-recipes/KnockKnock/KnockKnock.download.recipe`
    - `andrewvalentine-recipes/KnockKnock/KnockKnock.munki.recipe`
    - `apettinen-recipes/LuLu/LuLu.munki.recipe`
    - `apettinen-recipes/LuLu/LuLu.pkg.recipe`
    - `apettinen-recipes/LuLu/LuLu.download.recipe`
    - `wardsparadox-recipes/Objective-See, LLC/WhatsYourSign Installer.install.recipe`
    - `wardsparadox-recipes/Objective-See, LLC/WhatsYourSign Installer.pkg.recipe`
    - `wardsparadox-recipes/Objective-See, LLC/WhatsYourSign Installer.munki.recipe`
    - `wardsparadox-recipes/Objective-See, LLC/WhatsYourSign Installer.download.recipe`
- Similarly, there are existing Spectacle recipes in the jaharmi-recipes repo, and existing DockerDesktop and Zoom recipes in several repos.
- The Zoom download recipe in hansen-m-recipes that uses the "[IT Installer](https://support.zoom.us/hc/en-us/articles/115001799006)" generally recommended for deployment scenarios. Is there a reason your Zoom recipes don't use this method?
- I see you've included a `.pre-commit-hooks.yaml` file - that's only needed in a repository that hosts the hooks themselves. You can remove the file from your repo.
- In your `.pre-commit-config.yaml` file, you may want to include [this hook](https://github.com/autopkg/davidbpirie-recipes/blob/a511a4e4aaa181ce698c13c24962b36fd8febb4d/.pre-commit-config.yaml#L2-L14) that specifically checks AutoPkg recipes.

**Comment by jby** [comment]
Never mind, I'll might redo this later.
