### ISSUE TITLE
Fork my repo 

### ISSUE THREAD

**Issue by w0** [autopkg/autopkg#813]
Please fork my repo https://github.com/w0/autopkg-recipes

Thanks!

**Comment by homebysix** [comment]
A couple suggestions about the contents of this repo:

- I don't recommend using `%NAME%` as a component in an app path, as you're doing in many of your pkg recipes. If users of the recipe override the variable, it will break things that depend on that app path like the Copier and FileCreator steps. Instead, hard-code the actual app name in those paths.
- A few of the pkg recipes use the identifier prefix `com.github.w0.recipes` instead of the prefix `com.github.w0` that most recipes use.

Once you address those, I'll go ahead and create a fork. Thanks!

**Comment by w0** [comment]
Thanks for the feedback. I've made the suggested changes

**Comment by homebysix** [comment]
Repo created: https://github.com/autopkg/w0-recipes
