### ISSUE TITLE
Request to add repo

### ISSUE THREAD

**Issue by iancohn** [autopkg/autopkg#814]
Hi all, are you able to add my repo?
https://github.com/iancohn/autopkg-recipes.git

The new name can be iancohn-autopkg-recipes
Thanks!

**Comment by iancohn** [comment]
Hi!, just a friendly -bump- here. Hoping to have this setup in the near future.  Please let me know if there are any changes you'd suggest for the repo.

**Comment by homebysix** [comment]
I'll take a look at this soon.

**Comment by homebysix** [comment]
@iancohn Would iancohn-recipes be acceptable, to match existing repos' convention?

Running my pre-commit hooks on the recipes results in three suggestions, none of them major:

```
SeleniumEngine/SeleniumEngine.install.recipe: Processor EndOfCheckPhase is not conventional for this recipe type.
SeleniumEngine/SeleniumEngine.pkg.recipe: Convert from <!-- --> style comments to a Comment key.
SeleniumEngine/SeleniumEngine.pkg.recipe: Processor EndOfCheckPhase is not conventional for this recipe type.
```

**Comment by iancohn** [comment]
That name works fine,

Implemented recommendations.

Thanks!

**Comment by homebysix** [comment]
Thank you! Finally, I'd like to ask about the SeleniumEngine processor.

I understand it's a replacement for URLTextSearcher in cases where website elements might prevent `curl` from scraping the needed information. However, is this actually needed in a real-world scenario? I don't see any recipes (in your repo or otherwise) that reference SeleniumEngine, and the website provided as an example in the read me is `dictionary.com`, which doesn't appear to offer anything AutoPkg would be downloading.

AutoPkg recipes have sometimes worked around difficult-to-parse download pages by capturing the back-end API requests and responses needed to initiate the desired download. (A recent [example](https://github.com/autopkg/homebysix-recipes/blob/368979de333a9d0b2dd4433a28ec1461a644b911/Corel/CorelURLProvider.py) I worked on was for Corel products.) This seems to be a more robust and futureproof way of handling download automation, rather than relying on specific user-visible web elements to be predictable and idempotent.

Having a tangible use case for SeleniumEngine would help us understand and be more comfortable, since having your repo in the AutoPkg org means that SeleniumEngine will begin appearing in `autopkg search` results.

Aside from the processor itself, I also have questions about the SeleniumEngine family of recipes in your repo. Why is Chrome being downloaded together with SeleniumEngine [here](https://github.com/iancohn/autopkg-recipes/blob/968aaad0aa666fb5c38a238e13ff8fd9111b987a/SeleniumEngine/SeleniumEngine.download.recipe#L21)? If such downloads are necessary, I would expect to include at least CodeSignatureVerifier to help ensure their validity — however I'm not convinced the downloads are necessary. If deployment of SeleniumEngine itself is the goal, the deployment system (e.g. Jamf, Munki) should be able to handle presence and order of dependency installation.

Zooming in now to the SeleniumEngine.pkg recipe, can you elaborate on why this processor is being installed into the AutoPkg Python bundle? Other processors typically live in recipe repositories and have a "stub" recipe used to reference them from other recipes, which is much easier to maintain via `repo-update` rather than as a separate pkg install.

**Comment by iancohn** [comment]
Removed Selenium items from the main repo and added them to their own branch.

All valid questions. 
The version of Chrome and the Chrome WebDriver for the Selenium python module need to be compatible.  I've added a CodeSignatureVerifier for it.

I have it installing to the AutoPkg directory simply because that's how other similar modules were done (JSSImporter, AutoPkgBESEngine). Also, it needed to install the Selenium python module to the AutoPkg Python.  Additionally the version of Chrome and Chrome's webdriver that it uses needed to be stored somewhere and 'RecipeRepos' just didn't seem like the appropriate place, particularly for the webdriver. If indeed it is, I could certainly change that.

So for a more specific use case.. I added a Dell-BIOS.download recipe to repo under the new branch.  Admittedly, I also just found Dell's exposed API, so I'll be working on a non-Selenium processor that uses this.  

If you want, we can wait on this until I finish a shared processor for this particular one.

**Comment by iancohn** [comment]
@homebysix 
Hi again.  I had some time to rethink and add the recipes and SharedProcessor. 

Hoping to reconsider having these added.

**Comment by iancohn** [comment]
@homebysix  Is there anything I can do to move this along?

**Comment by homebysix** [comment]
New repo added: https://github.com/autopkg/iancohn-recipes

On brief read-through, I see there are a few Python syntax and linting issues in your shared processors, but nothing that looks like it would prevent execution. You may want to run `black` or your linter of choice to catch unused imports, `==` comparisons to booleans, and some mixed indentation issues.

Curious about what differentiates your VirusTotalAnalyzerV3 from [hjuutilainen's original](https://github.com/hjuutilainen/autopkg-virustotalanalyzer), and whether any of the differences would be suitable as PRs upstream?

**Comment by iancohn** [comment]
This one uses VT's v3 api as opposed to V2.  Also, I believe hjuutilainen's only submits the file and retrieves a small set of fields like name/link/ratio.

This one also allows some code signature validation for signed windows binaries/scripts, and a modestly large amount of information on the signature/cert chain
