### ISSUE TITLE
Autopkg Repo Add Request

### ISSUE THREAD

**Issue by inkeyes-coding** [autopkg/autopkg#849]
I'm requesting that you add my Autopkg recipe repo to the central group.

The URL to the repo is https://github.com/inkeyes-coding/inkeyes-recipes

I'd like to request that the name of the repo you create remains inkeyes-recipes

Thanks in advance!

**Comment by homebysix** [comment]
Hi @inkeyes-coding - Sorry for the delay. The recipes look good, although I think they duplicate some that are already available in the autopkg org. We try to discourage redundancy unless there's a good reason to offer another option to the community, as it makes searching for recipes harder.

- Mist-GUI.download - Seems to duplicate `com.github.zentralpro.download.mist` except it downloads the dmg instead of the pkg.
- Mist-GUI.munki - Seems to duplicate `com.github.zentralpro.munki.mist`.
- Zoom-ForIT.munki - Seems to duplicate `com.github.homebysix.munki.Zoom`.

**Comment by homebysix** [comment]
Hi @inkeyes-coding - Any update on this?

**Comment by inkeyes-coding** [comment]
Hi Elliot,

Please ignore my request for the time being. I've been unable to maintain that repo as of recently and it no longer makes sense to add it. Thanks for responding though.



Aug 15, 2023, 22:03 by ***@***.***:
