### ISSUE TITLE
3.0 RC1: running (non-trivial) recipes by path fails

### ISSUE THREAD

**Issue by gregneagle** [autopkg/autopkg#883]
**THIS IS ONLY INTENDED FOR AUTOPKG BETAS.**

**Describe the problem**
In autopkg 3.0 RC1, attempting to run a recipe by path where the recipe refers to a parent fails unless the parent is in the "recipe map". It fails even if the parent recipe is in the same directory as the (child) recipe being run.

**AutoPkg output**
autopkg run -v /Users/my_user/Library/AutoPkg/RecipeRepos/pkg-recipes/Keka/Keka.pkg.recipe
Looking for com.github.redacted.download.Keka...
Did not find com.github.redacted.download.Keka in recipe map
Search GitHub AutoPkg repos for a com.github.redacted.download.Keka recipe? [y/n]: n
We are not currently searching on-disk for recipes; if you intended to run a specific file not in the recipe map, please pass in an absolute file path instead.
Could not find parent recipe for /Users/my_user/Library/AutoPkg/RecipeRepos/pkg-recipes/Keka/Keka.pkg.recipe
**load_recipe time: 4.5761670419888105

Nothing downloaded, packaged or imported.

**Expected behavior**
autopkg should successfully run the recipe.

**Version (please complete the following information):**
 - OS version: 13.5.1
- AutoPkg Version: 3.0RC1

**Comment by jgstew** [comment]
I ran into this same issue. I was able to work around it by adding the path containing the recipes to the `RECIPE_SEARCH_DIRS` so that it would be built into the map.

In the above example it would mean you would have to have `/Users/my_user/Library/AutoPkg/RecipeRepos/pkg-recipes` in that value in the preferences and rebuild the map if not rebuilt already.

I'm not sure what a good solution to this is though. It might mean that a temporary map needs built following backwards from the currently referenced recipe, or fall back to the previous method of recipe lookup that does not depend on a map in these cases, even if it is much slower.

**Comment by nmcspadden** [comment]
This was very similar to https://github.com/autopkg/autopkg/issues/886 and was fixed with the same commit. The local path is added to the recipe map build when it tries to find a recipe not currently in the map. After that, if it can't find it within any of the search directories, it gives up (or asks Github...).
