### ISSUE TITLE
Fork jc0b-recipes

### ISSUE THREAD

**Issue by jc0b** [autopkg/autopkg#921]
Hello!

I'd like my [AutoPkg recipe repo](https://github.com/jc0b/jc0b-recipes.git) to be forked by AutoPkg.

Thanks!

**Comment by homebysix** [comment]
Hi @jc0b - A couple questions before I create this repo:

Many of the recipes in your repo seem to be very similar to those found elsewhere in the AutoPkg org. Duplicate recipes are discouraged in the autopkg org, so if your recipes do something different than the existing public recipes, I'd recommend adding some information to your recipes' descriptions detailing the differences (see [this example](https://github.com/autopkg/MLBZ521-recipes/blob/49c542915b1777ae3c2ffbf8a179cefb34d19299/NoMAD/NoMADLoginAD.jss.recipe#L5-L8)). Otherwise, see if you can use existing recipes as parents for any new ones. Partial list of existing recipes that look similar is below:

- jps3-recipes/Camtasia/Camtasia.download.recipe
- rtrouton-recipes/EndNote/EndNote20.download.recipe
- homebysix-recipes/GitHub/GitHubDesktop.download.recipe
- bochoven-recipes/JASP/JASP.download.recipe
- homebysix-recipes/Nindi Gill/LowProfile.download.recipe
- foigus-recipes/Microsoft/MicrosoftRemoteDesktop.munki.recipe (and two others)
- peshay-recipes/Mindjet/MindManager.download.recipe (and one other)
- apettinen-recipes/nmap/nmap.download.recipe
- psaintemarie-recipes/Postman-arm64/Postman-arm64.pkg.recipe (seems like the added versioning could be a PR to the psaintemarie-recipes repo)
- recipes/Praat/Praat.download.recipe
- gregneagle-recipes/SublimeText/SublimeText4.download.recipe

If I read correctly, your Terraform recipes are manually downloading the Intel and Apple Silicon versions of Terraform, then creating a pkg that installs one or the other depending on architecture? If this is actually what you want to do, I might suggest naming the recipes TerraformUniversal to distinguish them from the existing recipes in timsutton-recipes/HashiCorp/Terraform.download.recipe.

Your Fleet/fleetctl.pkg.recipe.yaml recipe appears to both download fleet and create a package. I would strongly recommend separating those tasks into separate download and pkg recipes, as is the convention in the autopkg org.

You might also consider adding a pre-commit config as described [here](https://www.elliotjordan.com/posts/pre-commit-02-autopkg/), which will catch a few common issues like this one:

```txt
JASP/JASP.munki.recipe.yaml: pkginfo key minimum_os_version should be type <class 'str'>, not type <class 'float'>
```

**Comment by jc0b** [comment]
Hey!

Most of the recipes you've listed are recipes I wrote ad-hoc for an old job, or I wrote them because I couldn't/didn't find an existing one at the time. I'm more than happy to add `DeprecationWarning`s to those recipes, and remove them from a potential repo under the autopkg org going forward. I'll also open PRs for any recipes that could use any of the differences in my own recipes.

The fleetctl and Terraform recipes have been fixed as per your suggestion, thanks!

Thanks for the tip on pre-commit as well - I've been meaning to set something up like this so that my recipes can be sanity checked before committing 😅 

Let me know if you'd rather I add DeprecationWarnings before or after a potential fork, thank you.

**Comment by homebysix** [comment]
Since the recipes aren't in the autopkg org yet, I'd recommend just deleting the ones that you want to remove so they aren't part of the new fork.

**Comment by jc0b** [comment]
Done, thanks. I converted the last XML recipe to YAML, and added the pre-commit hook config as well.

**Comment by homebysix** [comment]
Repo created: https://github.com/autopkg/jc0b-recipes
