### ISSUE TITLE
Offering a new recipe list

### ISSUE THREAD

**Issue by markkenny** [autopkg/autopkg#942]
Hi, just finished cleaning up all my recipes with homebysix pre-commit tools and an offering them for submission to be added to the autoPKG plist.

I've been writing my recipes in YAML to match my overrides and I've a number of recipes not available in https://github.com/autopkg Or are old or missing the PKG recipe. I know I should have offered a push request, but my work GitHub account doesn't let me clone external repo's or even report issues on public Git Hub.

I'm the Endpoint Engineer for Omnicom, so my recipes for are mostly for designers and web developers. 

Recipes I have that aren't duplicates; 

- Adobe WorkFront Proof
- HIVE
- Lucid (fixed last month)
- Monotype desktop application (deprecated)
- Monotype Fonts (new name)
- OmniPlan 4
- Rainbow (German Security tool)
- Scribe Desktop
- All the Tableau's in one place; Desktop, Prep, Public and Reader, Topaz DeNoise, GigaPixel, PhotoAI and Sharpen.

I've moved all my code to my personal repo so it's can be shared and used publicly. Thanks

https://github.com/markkenny/autopkg

**Comment by homebysix** [comment]
Hi @markkenny — Thanks for the submission!

In general, we discourage posting recipes that duplicate others already present in the AutoPkg org. This is mostly to simplify search results, as all your recipes would appear side by side with the existing recipes when people use `autopkg search` or GitHub web searches. Is there a way to separate out the duplicate recipes into their own repo, and leave the unique ones in this repo? If so, that would make it easier to go forward with offering your recipes in the AutoPkg org.

Additionally, there are some minor issues with the recipes that might be worth adjusting:
- `MinimumVersion` should be a string. In yaml, this requires surrounding the value with single or double quotes, or it will be treated as a float.
- Download recipes (like Monotypedesktopapplication.download and OpenWebStart.download) should conventionally contain an [EndOfCheckPhase](https://github.com/autopkg/autopkg/wiki/Processor-endofcheckphase) processor.
- OpenWebStart.pkg should use the actual app's name instead of `%NAME%.app` in the Copier process arguments, in order to allow administrators to override the name of the recipe without breaking its functionality.

**Comment by markkenny** [comment]
I'll move the duplicates and tidy up the others. Thank you for the feedback!

**Comment by markkenny** [comment]
Plenty of cleanup, no duplicates any more. Monotypedesktopapplication has bene deprecated in favour of Monotype Fonts now.

**Comment by homebysix** [comment]
New repo created, thanks!

https://github.com/autopkg/markkenny-recipes
