### ISSUE TITLE
Repo add bryanheinz-recipes

### ISSUE THREAD

**Issue by bryanheinz** [autopkg/autopkg#943]
I've written a few recipes that I'd like to contribute. Could you please add https://github.com/bryanheinz/bryanheinz-recipes

Many thanks!

-bryan

**Comment by homebysix** [comment]
Hi @bryanheinz — Thanks for the submission!

In general, we discourage posting recipes that duplicate others already present in the AutoPkg org. This is mostly to simplify search results, as all your recipes would appear side by side with the existing recipes when people use autopkg search or GitHub web searches. It looks like the following recipes duplicate others already in the org:
- AirBuddy
- Boop
- DiffusionBee
- Orion
- Webex

Also, I noticed the ParentRecipe for DiffusionBee.munki is listed as `DiffusionBee.download.recipe`. This should be a full recipe identifier in order to properly resolve.

**Comment by bryanheinz** [comment]
Thanks for the catch and sorry about the duplicates @homebysix. I'm not sure if I failed at searching or if I took too long to get my repo added that others were added in the meantime 😅

I've cleaned up the duplicates by entirely removing AirBuddy, Orion, and Webex. I deleted the Boop package and download recipes. And finally I've fixed the DiffusionBee parent download string.

Hopefully that cleans everything up, but please let me know if you find any more mistakes.

-bryan

**Comment by homebysix** [comment]
New repo ready to go: https://github.com/autopkg/bryanheinz-recipes
