### ISSUE TITLE
AppPkgCreator breaks code signature on info.plist

### ISSUE THREAD

**Issue by llamafilm** [autopkg/autopkg#948]
**Describe the problem**
After packaging a .app with AppPkgCreator, the code signature is broken. This can be seen in Apparency, and also by running `codesign --verify` after installing the pkg:

```
% codesign --verify /Applications/Telegraf.app 
/Applications/Telegraf.app: code object is not signed at all
In subcomponent: /Applications/Telegraf.app/Contents/info.plist
```

**AutoPkg output**
```
% autopkg run -v debug  --ignore-parent-trust-verification-errors  
Processing debug...
URLDownloader
URLDownloader: Storing new Last-Modified header: Mon, 01 Jul 2024 16:13:32 GMT
URLDownloader: Storing new ETag header: "b9e0cde3b2a08852565335fdcb8dbdc5-9"
URLDownloader: Downloaded /Users/ebalsley/Library/AutoPkg/Cache/debug/downloads/telegraf-1.31.1_darwin_arm64.dmg
AppPkgCreator
AppPkgCreator: Mounted disk image /Users/ebalsley/Library/AutoPkg/Cache/debug/downloads/telegraf-1.31.1_darwin_arm64.dmg
AppPkgCreator: Using path '/private/tmp/dmg.L86BkC/Telegraf.app' matched from globbed '/private/tmp/dmg.L86BkC/*.app'.
AppPkgCreator: Version: 1.31.1-99fcdc28
AppPkgCreator: BundleID: com.influxdata.telegraf
AppPkgCreator: Copied /private/tmp/dmg.L86BkC/Telegraf.app to /Users/ebalsley/Library/AutoPkg/Cache/debug/payload/Applications/Telegraf.app
AppPkgCreator: Connecting
AppPkgCreator: Sending packaging request
AppPkgCreator: Disconnecting
Receipt written to /Users/ebalsley/Library/AutoPkg/Cache/debug/receipts/debug-receipt-20240718-220413.plist

The following new items were downloaded:
    Download Path                                                                           
    -------------                                                                           
    /Users/ebalsley/Library/AutoPkg/Cache/debug/downloads/telegraf-1.31.1_darwin_arm64.dmg  

The following packages were built:
    Identifier               Version          Pkg Path                                                                  
    ----------               -------          --------                                                                  
    com.influxdata.telegraf  1.31.1-99fcdc28  /Users/ebalsley/Library/AutoPkg/Cache/debug/Telegraf-1.31.1-99fcdc28.pkg  
```

**Expected behavior**
The original .app in the downloaded DMG passes verification with no errors.  So the packaged app should too.
```
 % codesign --verify -v /Volumes/Telegraf/Telegraf.app 
/Volumes/Telegraf/Telegraf.app: valid on disk
/Volumes/Telegraf/Telegraf.app: satisfies its Designated Requirement
```

**Version (please complete the following information):**
 - OS version: 13.6.7
- AutoPkg Version:  2.7.3

This issue can be reproduced using this minimal example recipe:
```yaml
Identifier: debug
Input:
  NAME: telegraf
Process:
- Processor: URLDownloader
  Arguments:
    url: https://dl.influxdata.com/telegraf/releases/telegraf-1.31.1_darwin_arm64.dmg
- Processor: AppPkgCreator
```

**Comment by homebysix** [comment]
Interesting find, although it doesn't appear to be AutoPkg-specific. When I package Telegraf with quickpkg I see the same issue.

```
% quickpkg /Volumes/Telegraf/Telegraf.app --output /tmp/Telegraf.pkg
/tmp/Telegraf.pkg

% pkgutil --expand-full /tmp/Telegraf.pkg /tmp/Telegraf                                                                     

% codesign --verify --deep -vvv -r- /tmp/Telegraf/Payload/Telegraf.app 
/tmp/Telegraf/Payload/Telegraf.app: code object is not signed at all
In subcomponent: /private/tmp/Telegraf/Payload/Telegraf.app/Contents/info.plist
```

**Comment by rsaldinger** [comment]
I am pretty sure that the difference in code sign verification between the original and the packaged version is because xattrs are not getting preserved. That's pretty common, but why it matters here is a bit crazy.

The way that the Telegraf app [gets signed](https://github.com/influxdata/telegraf/blob/f11ead9980a82b4b99033a315e8158ac63217990/scripts/mac-signing.sh#L110) is pretty strange: first the actual Mach-O in Resources is signed (okay), then the main executable bash script in MacOS is signed directly (um), and then the Info.plist is copied into the bundle -- with the wrong case, as "info.plist" -- and the bundle itself is signed with --deep and --force. The upshot of all this is that the code signature on the bundle itself lives in the _CodeSignature directory, and the "info.plist" file has its **own** signature stored as xattrs! The bundle-level signature references the "info.plist" as being nested code that is separately signed. (The use of the wrong case on "info.plist" apparently circumvents all sorts of special cases in the code-signing mechanism that would normally handle Info.plist better than this.)

This verifies originally, because the bundle-level signature (in _CodeSignature/*) is valid, and when that references "info.plist" as being nested code, the xattrs are still on that file, and so verifying that works, too. In other words:

```
$ codesign --verify --verbose Telegraf.app/Contents/info.plist
Telegraf.app/Contents/info.plist: valid on disk
Telegraf.app/Contents/info.plist: satisfies its Designated Requirement

```
When this get packaged, the xattrs are archived into the package payload (they always are), but these are normally not preserved on the destination at installation time (nor by pkgbuild --expand-full). So then when you try to verify the bundle's code signature, it will still think that "info.plist" is something that should be separately signed, but its signature is gone.

[I mention all this here only because I know even _less_ about Telegraf than about Autopkg, so am probably not the one to be advocating for changes to the former. I only got here because @llamafilm asked me about why Apparency was reporting the code signature as not verified after going through packaging...]

**Comment by homebysix** [comment]
I wonder if there's an opportunity to help Telegraf's code signing practices align with standards, perhaps by submitting a PR to [this script](https://github.com/influxdata/telegraf/blob/master/scripts/mac-signing.sh)?

**Comment by rsaldinger** [comment]
> I wonder if there's an opportunity to help Telegraf's code signing practices align with standards, perhaps by submitting a PR to [this script](https://github.com/influxdata/telegraf/blob/master/scripts/mac-signing.sh)?

Almost certainly. That script is much more complicated than it needs to be, in addition to creating a bizarre result that isn't amenable to packaging.

I just didn't think I should be the one to initiate this, since I don't even really know what Telegraf is. But if @llamafilm wants to open a PR, I'm happy to add what I know.

**Comment by llamafilm** [comment]
Updating telegraf script makes sense to me, but unfortunately I don't have time to do that myself.

**Comment by rsaldinger** [comment]
@llamafilm Sorry, I actually wasn't _trying_ to suggest that you fix the script yourself, only that you open an issue against Telegraf explaining the problem that the current signature is causing. (My bad for using the wrong terminology; I am so little involved in GitHub projects that I maintain an archaic interpretation of "PR" as being a "problem report" rather than a "pull request"!)

**Comment by llamafilm** [comment]
Ah ok I see!  I've opened an issue here: https://github.com/influxdata/telegraf/issues/15646
